create table projects (
	id SERIAL PRIMARY KEY,
	title TEXT,
	color VARCHAR(50),
	city VARCHAR(50)
);
insert into projects (title, color, city) values ('est phasellus sit', 'Orange', 'Chaumont');
insert into projects (title, color, city) values ('augue vel accumsan', null, 'Chojnice');
insert into projects (title, color, city) values ('ridiculus', 'Purple', 'Ngou');
insert into projects (title, color, city) values ('curae mauris', 'Pink', 'Mets Parni');
insert into projects (title, color, city) values ('eu pede', 'Teal', 'Alingsås');
insert into projects (title, color, city) values ('cursus id turpis', 'Fuscia', 'Rauma');
insert into projects (title, color, city) values ('tempor', 'Crimson', 'Chumpi');
insert into projects (title, color, city) values ('vulputate', 'Crimson', 'Banraeaba Village');
insert into projects (title, color, city) values ('tellus nisi eu', null, 'Mari');
insert into projects (title, color, city) values ('fermentum donec ut', 'Pink', 'Pemba');
insert into projects (title, color, city) values ('sapien cum sociis', 'Goldenrod', 'Ntobo');
insert into projects (title, color, city) values ('sapien', 'Blue', 'Białobrzegi');
insert into projects (title, color, city) values ('mauris lacinia', 'Puce', 'Tunggulsari');
insert into projects (title, color, city) values ('non sodales sed', 'Khaki', 'Shambu');
insert into projects (title, color, city) values ('massa', 'Red', 'Mölndal');
insert into projects (title, color, city) values ('leo odio', null, 'Psebay');
insert into projects (title, color, city) values ('sit', 'Green', 'Yeliguan');
insert into projects (title, color, city) values ('augue vestibulum ante', 'Red', 'Magay');
insert into projects (title, color, city) values ('enim lorem ipsum', 'Pink', 'Praia de Mira');
insert into projects (title, color, city) values ('in sapien iaculis', 'Pink', 'Liqi');
insert into projects (title, color, city) values ('porta volutpat', null, 'Can-Avid');
insert into projects (title, color, city) values ('aenean', 'Yellow', 'Bakov nad Jizerou');
insert into projects (title, color, city) values ('dolor quis odio', 'Goldenrod', 'Chone');
insert into projects (title, color, city) values ('quis orci', 'Indigo', 'Fucun');
insert into projects (title, color, city) values ('parturient montes nascetur', 'Turquoise', 'Bulls');
insert into projects (title, color, city) values ('porta', 'Aquamarine', 'Lagoa');
insert into projects (title, color, city) values ('fringilla rhoncus mauris', 'Indigo', 'Ilha Solteira');
insert into projects (title, color, city) values ('mattis nibh', 'Khaki', 'Vitry-le-François');
insert into projects (title, color, city) values ('diam id', 'Goldenrod', 'Pontevedra');
insert into projects (title, color, city) values ('lobortis convallis', 'Pink', 'Wukari');
insert into projects (title, color, city) values ('placerat ante nulla', 'Fuscia', 'Xinó Neró');
insert into projects (title, color, city) values ('non ligula pellentesque', 'Red', 'Kajiki');
insert into projects (title, color, city) values ('sagittis', 'Turquoise', 'Kalloní');
insert into projects (title, color, city) values ('suspendisse accumsan tortor', 'Purple', 'Lloqan');
insert into projects (title, color, city) values ('phasellus in', null, 'Benchu');
insert into projects (title, color, city) values ('laoreet ut rhoncus', null, 'Itaporanga');
insert into projects (title, color, city) values ('vestibulum', 'Yellow', 'Zhuyeping');
insert into projects (title, color, city) values ('ultrices enim', 'Goldenrod', 'San Juan de la Maguana');
insert into projects (title, color, city) values ('id', 'Maroon', 'Stari Banovci');
insert into projects (title, color, city) values ('eget semper', 'Pink', 'Krajan Karangwage');
insert into projects (title, color, city) values ('blandit lacinia', 'Indigo', 'Zhuyu');
insert into projects (title, color, city) values ('a', 'Yellow', 'Yuyue');
insert into projects (title, color, city) values ('nisi venenatis tristique', 'Khaki', 'Laojie');
insert into projects (title, color, city) values ('tincidunt lacus at', 'Red', 'Betafo');
insert into projects (title, color, city) values ('turpis', 'Violet', 'Pokrovskoye-Streshnëvo');
insert into projects (title, color, city) values ('maecenas', 'Aquamarine', 'Comalapa');
insert into projects (title, color, city) values ('ante', 'Aquamarine', 'Criciúma');
insert into projects (title, color, city) values ('nulla quisque', null, 'Vila Nova de Gaia');
insert into projects (title, color, city) values ('maecenas tincidunt', 'Purple', 'Fuhai');
insert into projects (title, color, city) values ('blandit nam', 'Green', 'Oborniki Śląskie');
insert into projects (title, color, city) values ('tincidunt', 'Yellow', 'Xinzhou');
insert into projects (title, color, city) values ('aliquam lacus morbi', null, 'Melbourne');
insert into projects (title, color, city) values ('felis donec semper', 'Purple', 'Van Nuys');
insert into projects (title, color, city) values ('curabitur gravida', 'Goldenrod', 'Trondheim');
insert into projects (title, color, city) values ('dapibus augue', 'Goldenrod', 'Hanggan');
insert into projects (title, color, city) values ('eget orci', 'Turquoise', 'Jinping');
insert into projects (title, color, city) values ('quam sapien', 'Orange', 'Jäppilä');
insert into projects (title, color, city) values ('lobortis convallis', 'Crimson', 'Manaus');
insert into projects (title, color, city) values ('donec', 'Green', 'La Huerta');
insert into projects (title, color, city) values ('est', 'Khaki', 'Jiaoxie');
insert into projects (title, color, city) values ('at', 'Green', 'Áyioi Apóstoloi');
insert into projects (title, color, city) values ('felis eu', 'Purple', 'Independencia');
insert into projects (title, color, city) values ('ac', 'Khaki', 'Zdounky');
insert into projects (title, color, city) values ('congue etiam', 'Mauv', 'Kazanskoye');
insert into projects (title, color, city) values ('consequat varius integer', 'Indigo', 'Huangzhuang');
insert into projects (title, color, city) values ('odio curabitur convallis', 'Red', 'Karakabak');
insert into projects (title, color, city) values ('nonummy integer non', 'Puce', 'Cabadiangan');
insert into projects (title, color, city) values ('massa volutpat', null, 'Itajaí');
insert into projects (title, color, city) values ('odio', 'Red', 'Erie');
insert into projects (title, color, city) values ('pede', 'Red', 'Chojnów');
insert into projects (title, color, city) values ('parturient', 'Crimson', 'Xinshi');
insert into projects (title, color, city) values ('mauris sit amet', 'Crimson', 'Marcabal');
insert into projects (title, color, city) values ('est et', 'Purple', 'Sendung');
insert into projects (title, color, city) values ('platea dictumst etiam', 'Red', 'Angra do Heroísmo');
insert into projects (title, color, city) values ('elit', 'Turquoise', 'Gorgoram');
insert into projects (title, color, city) values ('amet consectetuer', 'Purple', 'Chibuto');
insert into projects (title, color, city) values ('vel nulla', 'Yellow', 'Huanggu');
insert into projects (title, color, city) values ('in sapien', 'Blue', 'Donskoye');
insert into projects (title, color, city) values ('elementum in hac', 'Turquoise', 'Pasirlaja');
insert into projects (title, color, city) values ('aliquet', 'Teal', 'Saint Joseph');
insert into projects (title, color, city) values ('massa donec dapibus', 'Green', 'Tigaherang');
insert into projects (title, color, city) values ('interdum', 'Pink', 'København');
insert into projects (title, color, city) values ('curae donec pharetra', null, 'Taipingying');
insert into projects (title, color, city) values ('hac habitasse', 'Violet', 'Chơn Thành');
insert into projects (title, color, city) values ('arcu', null, 'Qixian');
insert into projects (title, color, city) values ('luctus', 'Purple', 'Stockholm');
insert into projects (title, color, city) values ('est', 'Blue', 'Bronx');
insert into projects (title, color, city) values ('iaculis', 'Indigo', 'Shums’k');
insert into projects (title, color, city) values ('ipsum dolor', 'Orange', 'Temirtau');
insert into projects (title, color, city) values ('vel', 'Khaki', 'Gornyye Klyuchi');
insert into projects (title, color, city) values ('maecenas', 'Aquamarine', 'Cambará');
insert into projects (title, color, city) values ('molestie hendrerit', 'Yellow', 'Quy Đạt');
insert into projects (title, color, city) values ('velit donec diam', 'Teal', 'Fort Worth');
insert into projects (title, color, city) values ('blandit lacinia', 'Aquamarine', 'Chikwawa');
insert into projects (title, color, city) values ('nam nulla', null, 'Ježdovec');
insert into projects (title, color, city) values ('sed accumsan', 'Red', 'Apodi');
insert into projects (title, color, city) values ('mi', null, 'Chumikan');
insert into projects (title, color, city) values ('lobortis sapien', null, 'Lambangan Kulon');
insert into projects (title, color, city) values ('vitae ipsum', 'Fuscia', 'Nuamuzi');
insert into projects (title, color, city) values ('odio elementum', 'Crimson', 'San José');
insert into projects (title, color, city) values ('ante vestibulum', 'Pink', 'Sicaya');
insert into projects (title, color, city) values ('hac habitasse', 'Pink', 'Haebaru');
insert into projects (title, color, city) values ('convallis eget', null, 'El Paso');
insert into projects (title, color, city) values ('imperdiet sapien', 'Green', 'Zouparria do Monte');
insert into projects (title, color, city) values ('eu interdum eu', 'Pink', 'Blois');
insert into projects (title, color, city) values ('faucibus orci', 'Turquoise', 'Tianxingchang');
insert into projects (title, color, city) values ('rutrum', null, 'Tarutung');
insert into projects (title, color, city) values ('vulputate', 'Orange', 'Malamig');
insert into projects (title, color, city) values ('tortor', null, 'Puente Nacional');
insert into projects (title, color, city) values ('quisque', 'Yellow', 'Cihambali');
insert into projects (title, color, city) values ('amet consectetuer adipiscing', 'Red', 'Szczawnica');
insert into projects (title, color, city) values ('ipsum primis in', 'Purple', 'Tabio');
insert into projects (title, color, city) values ('in hac', 'Mauv', 'Tangtou');
insert into projects (title, color, city) values ('vestibulum ante ipsum', 'Red', 'Xunjian');
insert into projects (title, color, city) values ('magna', 'Blue', 'Vydreno');
insert into projects (title, color, city) values ('eget massa', 'Green', 'Caimitillo');
insert into projects (title, color, city) values ('ligula nec sem', null, 'Wangon');
insert into projects (title, color, city) values ('dui vel', 'Pink', 'Ichnya');
insert into projects (title, color, city) values ('quisque arcu', 'Orange', 'Ganghwa-gun');
insert into projects (title, color, city) values ('non', 'Orange', 'San Isidro');
insert into projects (title, color, city) values ('phasellus in felis', 'Red', 'Pogorzyce');
insert into projects (title, color, city) values ('habitasse platea', null, 'Pederneiras');
insert into projects (title, color, city) values ('pulvinar lobortis est', 'Violet', 'Pontevedra');
insert into projects (title, color, city) values ('et', 'Fuscia', 'Tarnowskie Góry');
insert into projects (title, color, city) values ('nulla elit', 'Puce', 'Batulawang');
insert into projects (title, color, city) values ('lorem id ligula', 'Turquoise', 'Boucinhas');
insert into projects (title, color, city) values ('consequat ut nulla', 'Orange', 'Masons Bay');
insert into projects (title, color, city) values ('cubilia curae mauris', 'Turquoise', 'Estacion');
insert into projects (title, color, city) values ('eros viverra eget', 'Orange', 'Mawlaik');
insert into projects (title, color, city) values ('convallis', 'Maroon', 'Svetlyy Yar');
insert into projects (title, color, city) values ('volutpat erat quisque', 'Goldenrod', 'Saraktash');
insert into projects (title, color, city) values ('suscipit ligula', 'Fuscia', 'Strängnäs');
insert into projects (title, color, city) values ('nullam orci pede', 'Fuscia', 'Huangzhu');
insert into projects (title, color, city) values ('eget', 'Violet', 'Sahagún');
insert into projects (title, color, city) values ('vestibulum', 'Red', 'Hamakita');
insert into projects (title, color, city) values ('adipiscing lorem vitae', 'Crimson', 'Nggesa');
insert into projects (title, color, city) values ('morbi sem mauris', null, 'Saginaw');
insert into projects (title, color, city) values ('id mauris', 'Violet', 'Odiongan');
insert into projects (title, color, city) values ('erat', 'Teal', 'Khŭjand');
insert into projects (title, color, city) values ('vestibulum aliquet ultrices', 'Khaki', 'Las Vegas');
insert into projects (title, color, city) values ('amet cursus', 'Green', 'Nakhon Luang');
insert into projects (title, color, city) values ('pharetra magna', 'Mauv', 'Presidente Epitácio');
insert into projects (title, color, city) values ('etiam pretium', 'Maroon', 'São Pedro de Trafaria');
insert into projects (title, color, city) values ('potenti', 'Maroon', 'Hexi');
insert into projects (title, color, city) values ('congue eget semper', 'Teal', 'Khyzy');
insert into projects (title, color, city) values ('rhoncus', 'Red', 'Villa Ascasubi');
insert into projects (title, color, city) values ('magna at nunc', null, 'Doāba');
insert into projects (title, color, city) values ('tempus vivamus in', 'Fuscia', 'Nizwá');
insert into projects (title, color, city) values ('justo in', 'Goldenrod', 'Changting');
insert into projects (title, color, city) values ('rutrum at lorem', 'Fuscia', 'Sucre');
insert into projects (title, color, city) values ('penatibus et', 'Khaki', 'Quintãs');
insert into projects (title, color, city) values ('vestibulum', 'Indigo', 'Sungai Raya');
insert into projects (title, color, city) values ('nisl nunc', 'Indigo', 'Zyukayka');
insert into projects (title, color, city) values ('quisque arcu', 'Turquoise', 'Imsida');
insert into projects (title, color, city) values ('justo', 'Violet', 'Letlhakeng');
insert into projects (title, color, city) values ('ut blandit', 'Teal', 'Jugezhuang');
insert into projects (title, color, city) values ('nulla mollis', 'Yellow', 'Nanyi');
insert into projects (title, color, city) values ('sollicitudin vitae consectetuer', 'Orange', 'La Roche-sur-Yon');
insert into projects (title, color, city) values ('semper sapien a', 'Green', 'Zhongxian');
insert into projects (title, color, city) values ('amet justo', 'Maroon', 'Altamira');
insert into projects (title, color, city) values ('tristique in', 'Green', 'Sredno Konjare');
insert into projects (title, color, city) values ('primis in', null, 'Hōfu');
insert into projects (title, color, city) values ('consequat', 'Khaki', 'La Peña');
insert into projects (title, color, city) values ('accumsan felis', 'Teal', 'Babakanloa');
insert into projects (title, color, city) values ('varius nulla', null, 'České Meziříčí');
insert into projects (title, color, city) values ('sit amet', 'Turquoise', 'Milanów');
insert into projects (title, color, city) values ('pellentesque eget', 'Maroon', 'Batawa');
insert into projects (title, color, city) values ('luctus et ultrices', 'Maroon', 'Springfield');
insert into projects (title, color, city) values ('iaculis congue vivamus', 'Indigo', 'Lop Buri');
insert into projects (title, color, city) values ('augue vel accumsan', 'Khaki', 'Fuzihe');
insert into projects (title, color, city) values ('id massa id', 'Indigo', 'Cabricán');
insert into projects (title, color, city) values ('integer tincidunt ante', 'Mauv', 'Mengla');
insert into projects (title, color, city) values ('rhoncus', 'Mauv', 'Ciomas');
insert into projects (title, color, city) values ('vel augue', 'Mauv', 'Zemun');
insert into projects (title, color, city) values ('magna', 'Pink', 'Sundsvall');
insert into projects (title, color, city) values ('est', 'Fuscia', 'Dukuhbadag');
insert into projects (title, color, city) values ('proin interdum', 'Indigo', 'Phaya Thai');
insert into projects (title, color, city) values ('donec diam neque', 'Mauv', 'San Jose');
insert into projects (title, color, city) values ('cum', 'Mauv', 'Kahabe');
insert into projects (title, color, city) values ('vel', null, 'Garden Grove');
insert into projects (title, color, city) values ('blandit mi', 'Fuscia', 'Jangkat');
insert into projects (title, color, city) values ('nulla ac', 'Purple', 'Marne-la-Vallée');
insert into projects (title, color, city) values ('vestibulum proin', 'Yellow', 'Horokhiv');
insert into projects (title, color, city) values ('nonummy maecenas', 'Orange', 'Baganha');
insert into projects (title, color, city) values ('in sapien', 'Indigo', 'Waeng Yai');
insert into projects (title, color, city) values ('orci luctus et', 'Blue', 'Lanos');
insert into projects (title, color, city) values ('integer pede justo', 'Fuscia', 'Mairinque');
insert into projects (title, color, city) values ('justo', 'Pink', 'New Haven');
insert into projects (title, color, city) values ('hac habitasse platea', 'Goldenrod', 'Hongqi');
insert into projects (title, color, city) values ('tempus vivamus', 'Khaki', 'Shūkat aş Şūfī');
insert into projects (title, color, city) values ('praesent', 'Teal', 'Puerto López');
insert into projects (title, color, city) values ('est', 'Goldenrod', 'Ráječko');
insert into projects (title, color, city) values ('luctus', 'Purple', 'Sanhe');
insert into projects (title, color, city) values ('neque sapien placerat', 'Maroon', 'Kallar Kahār');
insert into projects (title, color, city) values ('gravida sem', 'Turquoise', 'Kubang');
insert into projects (title, color, city) values ('cursus urna', null, 'Xiejiaya');
insert into projects (title, color, city) values ('erat id mauris', 'Mauv', 'Guaiúba');
insert into projects (title, color, city) values ('amet consectetuer', 'Turquoise', 'Arjona');
insert into projects (title, color, city) values ('at nulla suspendisse', 'Pink', 'Gereneng');
insert into projects (title, color, city) values ('tellus nulla ut', 'Fuscia', 'Cigembor');
insert into projects (title, color, city) values ('luctus ultricies', 'Aquamarine', 'Meshcherino');
insert into projects (title, color, city) values ('sollicitudin ut suscipit', 'Aquamarine', 'Ushuaia');
insert into projects (title, color, city) values ('pretium', null, 'Barberena');
insert into projects (title, color, city) values ('justo nec condimentum', 'Puce', 'Vila Chã');
insert into projects (title, color, city) values ('ultrices mattis', 'Green', 'Baihe');
insert into projects (title, color, city) values ('tempus vel', 'Fuscia', 'Jimeta');
insert into projects (title, color, city) values ('rhoncus dui', 'Red', 'Sa Kaeo');
insert into projects (title, color, city) values ('suspendisse potenti cras', 'Blue', 'Maralal');
insert into projects (title, color, city) values ('eros', 'Puce', 'Granada');
insert into projects (title, color, city) values ('quis justo maecenas', 'Turquoise', 'Tene');
insert into projects (title, color, city) values ('tempor', 'Khaki', 'Tržič');
insert into projects (title, color, city) values ('habitasse platea', 'Turquoise', 'Ares Tengah');
insert into projects (title, color, city) values ('mauris', 'Indigo', 'Sablé-sur-Sarthe');
insert into projects (title, color, city) values ('duis bibendum morbi', 'Violet', 'Shuanglu');
insert into projects (title, color, city) values ('in tempor turpis', 'Crimson', 'Além do Rio');
insert into projects (title, color, city) values ('lorem id', 'Puce', 'Tyringe');
insert into projects (title, color, city) values ('justo sollicitudin ut', 'Purple', 'Cilated');
insert into projects (title, color, city) values ('sapien ut', 'Blue', 'Sidi Yahya Ou Saad');
insert into projects (title, color, city) values ('dignissim', 'Puce', 'Keli');
insert into projects (title, color, city) values ('eget rutrum', 'Green', 'Léfka');
insert into projects (title, color, city) values ('laoreet', 'Khaki', 'Ōnojō');
insert into projects (title, color, city) values ('suspendisse potenti', 'Crimson', 'Kisai');
insert into projects (title, color, city) values ('duis bibendum felis', 'Red', 'Luzon');
insert into projects (title, color, city) values ('non mi', 'Aquamarine', 'Stebnyk');
insert into projects (title, color, city) values ('gravida nisi at', null, 'Nova Varoš');
insert into projects (title, color, city) values ('arcu', 'Indigo', 'Đạ Tẻh');
insert into projects (title, color, city) values ('etiam vel', 'Violet', 'Xiangcheng');
insert into projects (title, color, city) values ('nisl nunc', 'Teal', 'Belfast');
insert into projects (title, color, city) values ('turpis donec posuere', 'Green', 'Maria Cristina');
insert into projects (title, color, city) values ('mauris lacinia', null, 'Minas');
insert into projects (title, color, city) values ('praesent blandit', 'Aquamarine', 'Malinta');
insert into projects (title, color, city) values ('volutpat dui maecenas', 'Crimson', 'Baltimore');
insert into projects (title, color, city) values ('aenean auctor gravida', 'Turquoise', 'Agía Varvára');
insert into projects (title, color, city) values ('ultricies eu', 'Yellow', 'Bugo');
insert into projects (title, color, city) values ('id nulla', 'Pink', 'Los Angeles');
insert into projects (title, color, city) values ('amet consectetuer', 'Green', 'Hrazdan');
insert into projects (title, color, city) values ('ridiculus', null, 'Ziketan');
insert into projects (title, color, city) values ('nam nulla', 'Indigo', 'Wuyahe');
insert into projects (title, color, city) values ('malesuada in', 'Pink', 'Shinjō');
insert into projects (title, color, city) values ('justo in', 'Mauv', 'Marseille');
insert into projects (title, color, city) values ('porttitor lorem', 'Green', 'Tiannan');
insert into projects (title, color, city) values ('imperdiet et commodo', 'Violet', 'Mae Sot');
insert into projects (title, color, city) values ('id massa id', 'Teal', 'Buturlinovka');
insert into projects (title, color, city) values ('dui nec', 'Maroon', 'Jiangnan');
insert into projects (title, color, city) values ('nisi nam ultrices', 'Orange', 'Mlangali');
insert into projects (title, color, city) values ('lectus suspendisse', 'Puce', 'Apostolove');
insert into projects (title, color, city) values ('duis consequat dui', 'Blue', 'Hödrögö');
insert into projects (title, color, city) values ('sagittis dui vel', 'Indigo', 'Xingren');
insert into projects (title, color, city) values ('est lacinia', 'Orange', 'Stanišić');
insert into projects (title, color, city) values ('pede', 'Violet', 'Niechanowo');
insert into projects (title, color, city) values ('pede morbi', 'Crimson', 'Bendan');
insert into projects (title, color, city) values ('non velit', 'Green', 'Chojnów');
insert into projects (title, color, city) values ('in lacus curabitur', null, 'Bicurga');
insert into projects (title, color, city) values ('vestibulum', null, 'Xiangride');
insert into projects (title, color, city) values ('amet sem fusce', 'Aquamarine', 'Dandian');
insert into projects (title, color, city) values ('dapibus dolor', 'Blue', 'Kalungu');
insert into projects (title, color, city) values ('vulputate', 'Maroon', 'Chitré');
insert into projects (title, color, city) values ('odio', 'Maroon', 'Lapa do Lobo');
insert into projects (title, color, city) values ('potenti nullam porttitor', 'Yellow', 'Tuguan');
insert into projects (title, color, city) values ('laoreet', 'Mauv', 'Goúrnes');
insert into projects (title, color, city) values ('vulputate justo', 'Blue', 'Koreiz');
insert into projects (title, color, city) values ('hac habitasse platea', null, 'La Palma');
insert into projects (title, color, city) values ('platea', 'Khaki', 'Shanghu');
insert into projects (title, color, city) values ('at nulla', 'Indigo', 'Gaoleshan');
insert into projects (title, color, city) values ('amet', 'Orange', 'Padre Paraíso');
insert into projects (title, color, city) values ('donec', 'Red', 'Coronel Vivida');
insert into projects (title, color, city) values ('donec ut mauris', 'Turquoise', 'Kvissleby');
insert into projects (title, color, city) values ('tempus sit amet', 'Orange', 'Sōja');
insert into projects (title, color, city) values ('quis tortor id', 'Indigo', 'Singapore');
insert into projects (title, color, city) values ('posuere cubilia', 'Maroon', 'Dongxi');
insert into projects (title, color, city) values ('cubilia curae', 'Orange', 'La Quebrada');
insert into projects (title, color, city) values ('diam erat', 'Crimson', 'Hong’an');
insert into projects (title, color, city) values ('blandit ultrices', 'Goldenrod', 'Shidu');
insert into projects (title, color, city) values ('est phasellus sit', 'Red', 'Amsterdam Noord west');
insert into projects (title, color, city) values ('id mauris vulputate', null, 'Carreira');
insert into projects (title, color, city) values ('at turpis', 'Green', 'Saint Paul');
insert into projects (title, color, city) values ('sollicitudin ut', 'Crimson', 'Watunggong');
insert into projects (title, color, city) values ('consequat', 'Green', 'Mobile');
insert into projects (title, color, city) values ('purus phasellus', null, 'Ārān Bīdgol');
insert into projects (title, color, city) values ('quam', 'Teal', 'Pushkin');
insert into projects (title, color, city) values ('sodales', 'Teal', 'Huaitu');
insert into projects (title, color, city) values ('ut', 'Teal', 'Sarata');
insert into projects (title, color, city) values ('mattis', 'Indigo', 'Hrušovany u Brna');
insert into projects (title, color, city) values ('pede justo lacinia', 'Goldenrod', 'Rancanyenang');
insert into projects (title, color, city) values ('vestibulum rutrum', 'Turquoise', 'Barda');
insert into projects (title, color, city) values ('magnis dis parturient', 'Blue', 'Nakkila');
insert into projects (title, color, city) values ('parturient montes', 'Teal', 'Yakovlevo');
insert into projects (title, color, city) values ('aenean fermentum', 'Purple', 'Kalchevaya');
insert into projects (title, color, city) values ('pellentesque at', 'Crimson', 'Marseille');
insert into projects (title, color, city) values ('non mauris', 'Crimson', 'Cagliari');
insert into projects (title, color, city) values ('auctor gravida', 'Maroon', 'Qiewa');
insert into projects (title, color, city) values ('malesuada in imperdiet', 'Violet', 'Chartres');
insert into projects (title, color, city) values ('justo in', 'Turquoise', 'Hongshanyao');
insert into projects (title, color, city) values ('dolor vel', 'Khaki', 'Muli');
insert into projects (title, color, city) values ('curae nulla', 'Khaki', 'Guluoshan');
insert into projects (title, color, city) values ('sem', 'Puce', 'Dongzhou');
insert into projects (title, color, city) values ('curabitur gravida', 'Puce', 'Yaté-Barrage');
insert into projects (title, color, city) values ('eget rutrum', null, 'Campoalegre');
insert into projects (title, color, city) values ('aliquam quis', 'Khaki', 'Miejsce Piastowe');
insert into projects (title, color, city) values ('sem duis', 'Purple', 'Medeiros Neto');
insert into projects (title, color, city) values ('magnis dis parturient', 'Orange', 'Sucre');
insert into projects (title, color, city) values ('ipsum', 'Violet', 'Ludwin');
insert into projects (title, color, city) values ('morbi', 'Pink', 'Lomme');
insert into projects (title, color, city) values ('ultrices vel', 'Orange', 'Erie');
insert into projects (title, color, city) values ('volutpat', 'Khaki', 'Le Havre');
insert into projects (title, color, city) values ('ipsum', 'Pink', 'Hudson Bay');
insert into projects (title, color, city) values ('suspendisse potenti', 'Mauv', 'Mezhevoy');
insert into projects (title, color, city) values ('ultrices libero', 'Turquoise', 'Bascaron');
insert into projects (title, color, city) values ('ac tellus', 'Red', 'Karangnunggal');
insert into projects (title, color, city) values ('tristique fusce', 'Violet', 'Chengguan');
insert into projects (title, color, city) values ('tristique', 'Purple', 'Lyskovo');
insert into projects (title, color, city) values ('magna vulputate luctus', 'Goldenrod', 'Houston');
insert into projects (title, color, city) values ('parturient', 'Red', 'Killarney');
insert into projects (title, color, city) values ('turpis', 'Orange', 'Bordeaux');
insert into projects (title, color, city) values ('elementum ligula vehicula', 'Pink', 'Manolás');
insert into projects (title, color, city) values ('sed tristique', 'Mauv', 'Ciseureuheun');
insert into projects (title, color, city) values ('sit amet cursus', 'Maroon', 'Konārak');
insert into projects (title, color, city) values ('sit', null, 'Wajak');
insert into projects (title, color, city) values ('integer', 'Pink', 'San Pedro One');
insert into projects (title, color, city) values ('mattis', 'Puce', 'Daliu');
insert into projects (title, color, city) values ('cras in', 'Mauv', 'Xiaochi');
insert into projects (title, color, city) values ('tortor sollicitudin mi', 'Indigo', 'La Punta');
insert into projects (title, color, city) values ('aliquam sit', 'Fuscia', 'Lianyuan');
insert into projects (title, color, city) values ('vel nulla', 'Violet', 'Cishangang');
insert into projects (title, color, city) values ('accumsan', null, 'Dongshe');
insert into projects (title, color, city) values ('id lobortis convallis', 'Red', 'Calango');
insert into projects (title, color, city) values ('lacinia', 'Indigo', 'Malaga');
insert into projects (title, color, city) values ('mi nulla ac', 'Puce', 'Palilula');
insert into projects (title, color, city) values ('enim in tempor', null, 'Ledeunu');
insert into projects (title, color, city) values ('massa id', 'Pink', 'Thames');
insert into projects (title, color, city) values ('risus auctor sed', 'Teal', 'Kajansi');
insert into projects (title, color, city) values ('ornare consequat', 'Violet', 'Golubac');
insert into projects (title, color, city) values ('sit', null, 'Chaguaní');
insert into projects (title, color, city) values ('nulla', 'Blue', 'Fatufaun');
insert into projects (title, color, city) values ('quisque arcu libero', 'Purple', 'Regimin');
insert into projects (title, color, city) values ('etiam justo', 'Maroon', 'Guolemude');
insert into projects (title, color, city) values ('nisl nunc rhoncus', 'Pink', 'Baohe');
insert into projects (title, color, city) values ('sed', 'Indigo', 'Ust’-Dzheguta');
insert into projects (title, color, city) values ('nonummy integer', 'Blue', 'Vylkove');
insert into projects (title, color, city) values ('vitae nisi nam', 'Indigo', 'Keelung');
insert into projects (title, color, city) values ('tincidunt nulla', 'Yellow', 'Kolyshley');
insert into projects (title, color, city) values ('amet nulla', 'Purple', 'Sancha');
insert into projects (title, color, city) values ('morbi non lectus', 'Violet', 'Margarita');
insert into projects (title, color, city) values ('parturient montes', 'Khaki', 'Tānsen');
insert into projects (title, color, city) values ('pretium quis', 'Crimson', 'Calangain');
insert into projects (title, color, city) values ('pede ullamcorper', null, 'Santa Cruz');
insert into projects (title, color, city) values ('curae duis faucibus', 'Yellow', 'Zubří');
insert into projects (title, color, city) values ('in sapien', 'Pink', 'Yanagawamachi-saiwaichō');
insert into projects (title, color, city) values ('felis eu', 'Turquoise', 'Blagoevgrad');
insert into projects (title, color, city) values ('curae', 'Violet', 'Yanmenkou');
insert into projects (title, color, city) values ('nulla sed', 'Fuscia', 'Gading');
insert into projects (title, color, city) values ('in magna bibendum', null, 'Kandete');
insert into projects (title, color, city) values ('eros', 'Blue', 'Tikhoretsk');
insert into projects (title, color, city) values ('condimentum neque sapien', 'Mauv', 'Kakegawa');
insert into projects (title, color, city) values ('vel est', 'Khaki', 'Ouanaminthe');
insert into projects (title, color, city) values ('ac', 'Violet', 'La Habana Vieja');
insert into projects (title, color, city) values ('donec odio', 'Purple', 'Woodstock');
insert into projects (title, color, city) values ('non lectus aliquam', 'Mauv', 'Shibīn al Kawm');
insert into projects (title, color, city) values ('ultricies eu', 'Puce', 'Laban');
insert into projects (title, color, city) values ('elementum ligula', 'Pink', 'Shardara');
insert into projects (title, color, city) values ('diam erat fermentum', 'Goldenrod', 'Choco');
insert into projects (title, color, city) values ('ut suscipit a', null, 'Cangkuang');
insert into projects (title, color, city) values ('at lorem integer', 'Mauv', 'La Romana');
insert into projects (title, color, city) values ('mauris enim leo', 'Blue', 'Penedo');
insert into projects (title, color, city) values ('et eros vestibulum', 'Teal', 'Qinlan');
insert into projects (title, color, city) values ('posuere felis sed', 'Goldenrod', 'Wawer');
insert into projects (title, color, city) values ('nibh in hac', 'Purple', 'Bang Pahan');
insert into projects (title, color, city) values ('aliquet maecenas', null, 'Ciechocin');
insert into projects (title, color, city) values ('maecenas rhoncus aliquam', 'Goldenrod', 'Ciulu');
insert into projects (title, color, city) values ('nunc', 'Goldenrod', 'Simenqian');
insert into projects (title, color, city) values ('diam neque', 'Green', 'Podporozh’ye');
insert into projects (title, color, city) values ('integer non velit', 'Teal', 'Santa Rita');
insert into projects (title, color, city) values ('lectus in quam', 'Crimson', 'Midrand');
insert into projects (title, color, city) values ('sit amet nunc', 'Teal', 'Hawassa');
insert into projects (title, color, city) values ('nulla facilisi cras', null, 'Oetuke');
insert into projects (title, color, city) values ('mus', null, 'Gongfang');
insert into projects (title, color, city) values ('semper', 'Pink', 'Beiling');
insert into projects (title, color, city) values ('sollicitudin vitae', 'Red', 'Klishkivtsi');
insert into projects (title, color, city) values ('rutrum', 'Blue', 'Shuanghe');
insert into projects (title, color, city) values ('velit eu est', 'Indigo', 'Zboriv');
insert into projects (title, color, city) values ('velit', 'Crimson', 'Maastricht');
insert into projects (title, color, city) values ('ante vestibulum ante', 'Turquoise', 'Bernay');
insert into projects (title, color, city) values ('morbi non quam', null, 'Biryulëvo Zapadnoye');
insert into projects (title, color, city) values ('nullam', 'Pink', 'Gambarjati');
insert into projects (title, color, city) values ('erat vestibulum', 'Red', 'Amizmiz');
insert into projects (title, color, city) values ('augue vestibulum rutrum', 'Pink', 'Frösön');
insert into projects (title, color, city) values ('lobortis est phasellus', 'Yellow', 'Požarevac');
insert into projects (title, color, city) values ('cras', 'Pink', 'Otan Aiyegbaju');
insert into projects (title, color, city) values ('ipsum ac tellus', 'Violet', 'Wellington');
insert into projects (title, color, city) values ('dolor sit', 'Violet', 'Birayang');
insert into projects (title, color, city) values ('integer aliquet', 'Violet', 'Ancasti');
insert into projects (title, color, city) values ('feugiat et eros', 'Fuscia', 'Dandai');
insert into projects (title, color, city) values ('condimentum id luctus', null, 'Aragua de Barcelona');
insert into projects (title, color, city) values ('neque', 'Puce', 'Tominian');
insert into projects (title, color, city) values ('phasellus sit', 'Green', 'Koblain');
insert into projects (title, color, city) values ('posuere cubilia', 'Aquamarine', 'Maceió');
insert into projects (title, color, city) values ('tempor convallis', 'Orange', 'Fagersta');
insert into projects (title, color, city) values ('praesent lectus vestibulum', 'Pink', 'Ganyesa');
insert into projects (title, color, city) values ('volutpat dui maecenas', 'Fuscia', 'Xipu');
insert into projects (title, color, city) values ('rhoncus', 'Maroon', 'Pedreira');
insert into projects (title, color, city) values ('ultrices aliquet maecenas', 'Crimson', 'Prachatice');
insert into projects (title, color, city) values ('mollis molestie', 'Fuscia', 'Sandaoba');
insert into projects (title, color, city) values ('pellentesque eget nunc', 'Crimson', 'Yangp''yŏng');
insert into projects (title, color, city) values ('lacinia', 'Mauv', 'Changtang');
insert into projects (title, color, city) values ('orci mauris lacinia', null, 'Kōnosu');
insert into projects (title, color, city) values ('consequat varius', 'Indigo', 'Growong Kidul');
insert into projects (title, color, city) values ('posuere cubilia', null, 'Xiangang');
insert into projects (title, color, city) values ('ante vivamus tortor', null, 'Pittsburgh');
insert into projects (title, color, city) values ('orci luctus et', 'Khaki', 'Cabo Frio');
insert into projects (title, color, city) values ('eu massa', 'Goldenrod', 'Główczyce');
insert into projects (title, color, city) values ('duis at', 'Red', 'Helsingborg');
insert into projects (title, color, city) values ('nulla mollis', null, 'Semamung');
insert into projects (title, color, city) values ('magnis dis', 'Turquoise', 'Ayagoz');
insert into projects (title, color, city) values ('sem praesent', 'Green', 'Oguta');
insert into projects (title, color, city) values ('vel ipsum', 'Aquamarine', 'Xueshan');
insert into projects (title, color, city) values ('blandit ultrices enim', 'Blue', 'Waikambila');
insert into projects (title, color, city) values ('posuere', 'Mauv', 'La Sierpe');
insert into projects (title, color, city) values ('orci', 'Mauv', 'Grammatikó');
insert into projects (title, color, city) values ('est donec', 'Aquamarine', 'Sidareja');
insert into projects (title, color, city) values ('metus', 'Blue', 'Dimona');
insert into projects (title, color, city) values ('elementum', 'Blue', 'Nakanojōmachi');
insert into projects (title, color, city) values ('at lorem integer', 'Crimson', 'Huangcaotuo');
insert into projects (title, color, city) values ('mauris', null, 'Kajisara');
insert into projects (title, color, city) values ('quis orci eget', 'Turquoise', 'Rízoma');
insert into projects (title, color, city) values ('eros elementum pellentesque', 'Fuscia', 'Imeni Zhelyabova');
insert into projects (title, color, city) values ('habitasse', 'Teal', 'Ambanja');
insert into projects (title, color, city) values ('vestibulum', 'Pink', 'Narita');
insert into projects (title, color, city) values ('mi in', 'Turquoise', 'Itsukaichi');
insert into projects (title, color, city) values ('pharetra magna ac', 'Orange', 'Město');
insert into projects (title, color, city) values ('sed justo pellentesque', 'Goldenrod', 'Songkar B');
insert into projects (title, color, city) values ('duis', null, 'Stockholm');
insert into projects (title, color, city) values ('vitae ipsum aliquam', 'Red', 'Tākestān');
insert into projects (title, color, city) values ('massa', 'Teal', 'Dongshui');
insert into projects (title, color, city) values ('egestas metus', 'Purple', 'Ibirama');
insert into projects (title, color, city) values ('lacinia eget', 'Indigo', 'Odiong');
insert into projects (title, color, city) values ('ultrices posuere cubilia', 'Teal', 'Wijewo');
insert into projects (title, color, city) values ('non', 'Fuscia', 'Hněvotín');
insert into projects (title, color, city) values ('tortor sollicitudin mi', 'Orange', 'Lancaster');
insert into projects (title, color, city) values ('orci vehicula', 'Green', 'Frederico Westphalen');
insert into projects (title, color, city) values ('pellentesque volutpat dui', null, 'Oleszyce');
insert into projects (title, color, city) values ('imperdiet sapien urna', 'Turquoise', 'Yishi');
insert into projects (title, color, city) values ('dapibus at diam', 'Pink', 'Jiulonggang');
insert into projects (title, color, city) values ('aliquam convallis nunc', 'Green', 'Sumberan');
insert into projects (title, color, city) values ('eu', 'Khaki', 'Jinshan');
insert into projects (title, color, city) values ('viverra', 'Fuscia', 'Andrushivka');
insert into projects (title, color, city) values ('elit proin', 'Puce', 'Yangqiao');
insert into projects (title, color, city) values ('amet', 'Khaki', 'Ngromo');
insert into projects (title, color, city) values ('lobortis sapien', 'Aquamarine', 'Varkaus');
insert into projects (title, color, city) values ('at ipsum', 'Crimson', 'Danderyd');
insert into projects (title, color, city) values ('suscipit', null, 'Mertzig');
insert into projects (title, color, city) values ('ultrices mattis', 'Pink', 'Dallas');
insert into projects (title, color, city) values ('vestibulum aliquet ultrices', 'Green', 'Al Qaţn');
insert into projects (title, color, city) values ('vestibulum', 'Crimson', 'Banes');
insert into projects (title, color, city) values ('quisque', 'Pink', 'Pacucha');
insert into projects (title, color, city) values ('sed augue aliquam', 'Green', 'Buzet');
insert into projects (title, color, city) values ('pede', 'Red', 'Yangkou');
insert into projects (title, color, city) values ('cubilia', null, 'Ferkessédougou');
insert into projects (title, color, city) values ('aenean lectus pellentesque', null, 'Zhaolingpu');
insert into projects (title, color, city) values ('tortor id', 'Pink', 'Citeureup');
insert into projects (title, color, city) values ('ridiculus mus etiam', 'Blue', 'Kapasan');
insert into projects (title, color, city) values ('venenatis', 'Puce', 'Chekmagush');
insert into projects (title, color, city) values ('curabitur convallis duis', 'Blue', 'Orizari');
insert into projects (title, color, city) values ('nisi', null, 'Katyuzhanka');
insert into projects (title, color, city) values ('sit', 'Teal', 'Palue');
insert into projects (title, color, city) values ('blandit ultrices enim', 'Purple', 'Puerto Boyacá');
insert into projects (title, color, city) values ('scelerisque mauris sit', 'Khaki', 'Karangagung Timur');
insert into projects (title, color, city) values ('cubilia curae', 'Crimson', 'Fuvahmulah');
insert into projects (title, color, city) values ('vivamus vel', 'Crimson', 'Kampong Cham');
insert into projects (title, color, city) values ('nibh in lectus', 'Khaki', 'Ovalle');
insert into projects (title, color, city) values ('volutpat dui maecenas', 'Red', 'Buenos Aires');
insert into projects (title, color, city) values ('erat curabitur gravida', 'Blue', 'Toulouse');
insert into projects (title, color, city) values ('varius integer', 'Puce', 'Gangu Chengguanzhen');
insert into projects (title, color, city) values ('dolor vel est', null, 'Heping');
insert into projects (title, color, city) values ('habitasse platea', 'Puce', 'Lorient');
insert into projects (title, color, city) values ('non mi', 'Violet', 'Castleknock');
insert into projects (title, color, city) values ('luctus nec molestie', 'Mauv', 'Meaux');
insert into projects (title, color, city) values ('dis parturient montes', null, 'Ojrzeń');
insert into projects (title, color, city) values ('lacus at velit', 'Pink', 'København');
insert into projects (title, color, city) values ('eu orci mauris', 'Puce', 'Spirit River');
insert into projects (title, color, city) values ('mus', 'Goldenrod', 'Châteauroux');
insert into projects (title, color, city) values ('adipiscing elit', 'Turquoise', 'Zhanbei');
insert into projects (title, color, city) values ('eget congue', 'Red', 'Wushan');
insert into projects (title, color, city) values ('consequat dui', 'Turquoise', 'Longfengba');
insert into projects (title, color, city) values ('dolor sit amet', 'Maroon', 'Wudil');
insert into projects (title, color, city) values ('pellentesque viverra', 'Crimson', 'Cential');
insert into projects (title, color, city) values ('suspendisse accumsan', 'Purple', 'Hakha');
insert into projects (title, color, city) values ('nulla', null, 'Suai');
insert into projects (title, color, city) values ('cum sociis natoque', 'Orange', 'Balai');
insert into projects (title, color, city) values ('pellentesque', 'Turquoise', 'Baimaqiao');
insert into projects (title, color, city) values ('mollis molestie lorem', 'Pink', 'Talangbetutu');
insert into projects (title, color, city) values ('nibh in lectus', 'Indigo', 'Timrat');
insert into projects (title, color, city) values ('pretium', 'Mauv', 'Buriwutung');
insert into projects (title, color, city) values ('amet erat nulla', 'Maroon', 'Hangkou');
insert into projects (title, color, city) values ('velit id', 'Aquamarine', 'Beauvais');
insert into projects (title, color, city) values ('tellus in', 'Crimson', 'Satuba');
insert into projects (title, color, city) values ('dui maecenas tristique', 'Khaki', 'Qiangqinxue');
insert into projects (title, color, city) values ('erat', 'Maroon', 'Toba');
insert into projects (title, color, city) values ('consequat morbi a', 'Pink', 'Banjar Dauhpura');
insert into projects (title, color, city) values ('vel augue vestibulum', 'Red', 'Serra');
insert into projects (title, color, city) values ('porttitor lacus', 'Yellow', 'Sujji');
insert into projects (title, color, city) values ('nulla pede ullamcorper', null, 'Manaloal');
insert into projects (title, color, city) values ('augue', 'Teal', 'Churovichi');
insert into projects (title, color, city) values ('tincidunt eget tempus', null, 'Gongchang Zhen');
insert into projects (title, color, city) values ('sapien', 'Maroon', 'Pyatovskiy');
insert into projects (title, color, city) values ('praesent', null, 'Barcelona');
insert into projects (title, color, city) values ('mus', 'Puce', 'Campo Verde');
insert into projects (title, color, city) values ('praesent lectus', null, 'Norfolk');
insert into projects (title, color, city) values ('sit amet eleifend', 'Pink', 'Namayingo');
insert into projects (title, color, city) values ('lacus at velit', 'Purple', 'Custódia');
insert into projects (title, color, city) values ('nisl', 'Indigo', 'Getung');
insert into projects (title, color, city) values ('dapibus duis', null, 'Hengshi');
insert into projects (title, color, city) values ('est phasellus sit', null, 'Kubang');
insert into projects (title, color, city) values ('blandit', null, 'Estância Velha');
insert into projects (title, color, city) values ('in tempor', 'Mauv', 'Xazgat');
insert into projects (title, color, city) values ('vestibulum', 'Goldenrod', 'Esperanza');
insert into projects (title, color, city) values ('quam a', 'Aquamarine', 'South Bend');
insert into projects (title, color, city) values ('et ultrices posuere', 'Orange', 'Providencia');
insert into projects (title, color, city) values ('commodo', 'Maroon', 'Shiyan');
insert into projects (title, color, city) values ('eleifend pede libero', null, 'Dąbrowa');
insert into projects (title, color, city) values ('tempus sit', 'Fuscia', 'Kota Kinabalu');
insert into projects (title, color, city) values ('faucibus orci', null, 'Schœlcher');
insert into projects (title, color, city) values ('semper est', 'Teal', 'Dulangan');
insert into projects (title, color, city) values ('sed', 'Yellow', 'Portela');
insert into projects (title, color, city) values ('sit', 'Purple', 'Ibiporã');
insert into projects (title, color, city) values ('erat quisque erat', 'Fuscia', 'Talok');
insert into projects (title, color, city) values ('libero nam', 'Orange', 'Oliveira');
insert into projects (title, color, city) values ('id ligula suspendisse', 'Teal', 'Anyuan');
insert into projects (title, color, city) values ('suspendisse ornare', 'Orange', 'Mudian');
insert into projects (title, color, city) values ('eu est congue', 'Mauv', 'Safed');
insert into projects (title, color, city) values ('erat curabitur gravida', 'Orange', 'Temperak');
insert into projects (title, color, city) values ('morbi', 'Violet', 'Pandansari');
insert into projects (title, color, city) values ('orci mauris lacinia', null, 'Hujiaba');
insert into projects (title, color, city) values ('amet erat nulla', 'Teal', 'Belung Satu');
insert into projects (title, color, city) values ('lacus at velit', 'Crimson', 'Åkersberga');
insert into projects (title, color, city) values ('metus', 'Goldenrod', 'Rędziny');
insert into projects (title, color, city) values ('donec semper', 'Blue', 'Pulong Gubat');
insert into projects (title, color, city) values ('est', 'Green', 'Ambositra');
insert into projects (title, color, city) values ('justo aliquam', 'Purple', 'Carmo do Paranaíba');
insert into projects (title, color, city) values ('quis', null, 'Toledo');
insert into projects (title, color, city) values ('justo pellentesque viverra', 'Indigo', 'Cotabambas');
insert into projects (title, color, city) values ('duis ac', 'Green', 'Balzers');
insert into projects (title, color, city) values ('nunc', null, 'Haczów');
insert into projects (title, color, city) values ('vestibulum ante ipsum', 'Orange', 'Avdzaga');
insert into projects (title, color, city) values ('ultrices posuere', null, 'Gowurdak');
insert into projects (title, color, city) values ('quis', 'Purple', 'Bankim');
insert into projects (title, color, city) values ('quis', 'Goldenrod', 'La Salud');
insert into projects (title, color, city) values ('sed interdum', 'Mauv', 'Los Charrúas');
insert into projects (title, color, city) values ('morbi non quam', 'Aquamarine', 'San Nicolas');
insert into projects (title, color, city) values ('fusce congue', 'Red', 'Kuala Terengganu');
insert into projects (title, color, city) values ('risus praesent', 'Goldenrod', 'Dayou');
insert into projects (title, color, city) values ('tempor turpis', 'Pink', 'La Ceja');
insert into projects (title, color, city) values ('dolor morbi vel', 'Mauv', 'Nam Khun');
insert into projects (title, color, city) values ('cum', null, 'Sagara');
insert into projects (title, color, city) values ('sed', 'Aquamarine', 'Zea');
insert into projects (title, color, city) values ('habitasse', 'Puce', 'Xindong');
insert into projects (title, color, city) values ('elit proin interdum', 'Aquamarine', 'Villa del Rosario');
insert into projects (title, color, city) values ('ante vel ipsum', 'Crimson', 'Potštát');
insert into projects (title, color, city) values ('rutrum neque aenean', null, 'Portoviejo');
insert into projects (title, color, city) values ('augue vestibulum', 'Teal', 'Peterborough');
insert into projects (title, color, city) values ('ut ultrices', 'Aquamarine', 'Beigou');
insert into projects (title, color, city) values ('tellus semper interdum', 'Yellow', 'Beigang');
insert into projects (title, color, city) values ('orci', 'Orange', 'Emiliano Zapata');
insert into projects (title, color, city) values ('neque duis', 'Blue', 'San Sebastian');
insert into projects (title, color, city) values ('morbi sem mauris', 'Fuscia', 'Novyy Urgal');
insert into projects (title, color, city) values ('integer non', 'Fuscia', 'Negombo');
insert into projects (title, color, city) values ('venenatis lacinia aenean', 'Fuscia', 'Peremyshl’');
insert into projects (title, color, city) values ('consectetuer eget rutrum', 'Blue', 'Thị Trấn Thuận Châu');
insert into projects (title, color, city) values ('lectus pellentesque at', 'Blue', 'Whittlesea');
insert into projects (title, color, city) values ('morbi porttitor lorem', null, 'Teresa');
insert into projects (title, color, city) values ('eget nunc donec', 'Violet', 'Bintang');
insert into projects (title, color, city) values ('eu tincidunt', 'Pink', 'Kombapari');
insert into projects (title, color, city) values ('vestibulum ante', 'Teal', 'Koslan');
insert into projects (title, color, city) values ('mollis', 'Crimson', 'Shkotovo');
insert into projects (title, color, city) values ('gravida', null, 'Ylöjärvi');
insert into projects (title, color, city) values ('a nibh', 'Green', 'Roma');
insert into projects (title, color, city) values ('lobortis est phasellus', 'Mauv', 'Altanbulag');
insert into projects (title, color, city) values ('eros elementum', 'Maroon', 'São Joaquim da Barra');
insert into projects (title, color, city) values ('maecenas rhoncus aliquam', 'Green', 'Gedaliang');
insert into projects (title, color, city) values ('curabitur', 'Maroon', 'Namora');
insert into projects (title, color, city) values ('primis in faucibus', 'Goldenrod', 'Karangnongko');
insert into projects (title, color, city) values ('in congue etiam', 'Yellow', 'Araruama');
insert into projects (title, color, city) values ('mattis odio donec', 'Green', 'Bang Rakam');
insert into projects (title, color, city) values ('ut blandit', 'Aquamarine', 'Zhangjiafan');
insert into projects (title, color, city) values ('ipsum primis in', 'Mauv', 'Nanterre');
insert into projects (title, color, city) values ('dui nec', 'Aquamarine', 'Calingcing');
insert into projects (title, color, city) values ('elit', 'Maroon', 'Songea');
insert into projects (title, color, city) values ('mattis', 'Yellow', 'Tamel');
insert into projects (title, color, city) values ('sed', 'Fuscia', 'Fort Worth');
insert into projects (title, color, city) values ('eros vestibulum', 'Fuscia', 'Benger');
insert into projects (title, color, city) values ('nulla', 'Puce', 'Carman');
insert into projects (title, color, city) values ('montes', 'Yellow', 'Vagonoremont');
insert into projects (title, color, city) values ('hac', 'Orange', 'Watuagung');
insert into projects (title, color, city) values ('nec', 'Blue', 'Canggetelo');
insert into projects (title, color, city) values ('leo pellentesque', 'Fuscia', 'Zarzal');
insert into projects (title, color, city) values ('in', 'Violet', 'Solnice');
insert into projects (title, color, city) values ('magna ac', 'Teal', 'Lourdes');
insert into projects (title, color, city) values ('vitae consectetuer eget', 'Indigo', 'Witkowo');
insert into projects (title, color, city) values ('venenatis', 'Indigo', 'Shenji');
insert into projects (title, color, city) values ('turpis elementum ligula', 'Aquamarine', 'Belogorsk');
insert into projects (title, color, city) values ('nam ultrices', 'Aquamarine', 'Zhanxu');
insert into projects (title, color, city) values ('eget orci vehicula', 'Maroon', 'Géfyra');
insert into projects (title, color, city) values ('sociis', 'Aquamarine', 'Bao’an');
insert into projects (title, color, city) values ('erat curabitur', 'Turquoise', 'Solânea');
insert into projects (title, color, city) values ('volutpat in congue', 'Khaki', 'Ganhe');
insert into projects (title, color, city) values ('in purus eu', null, 'Kassiri');
insert into projects (title, color, city) values ('vel accumsan', 'Blue', 'Varser');
insert into projects (title, color, city) values ('lobortis', 'Khaki', 'Sarreguemines');
insert into projects (title, color, city) values ('lobortis ligula', 'Orange', 'Tabalong');
insert into projects (title, color, city) values ('felis donec', 'Violet', 'Malita');
insert into projects (title, color, city) values ('non', 'Orange', 'Sukatani');
insert into projects (title, color, city) values ('pellentesque ultrices phasellus', 'Indigo', 'Phù Cát');
insert into projects (title, color, city) values ('leo odio', 'Khaki', 'Osięciny');
insert into projects (title, color, city) values ('augue aliquam erat', 'Maroon', 'Rokytne');
insert into projects (title, color, city) values ('massa', null, 'Alquízar');
insert into projects (title, color, city) values ('gravida nisi at', 'Mauv', 'Petaluma');
insert into projects (title, color, city) values ('dolor sit', 'Khaki', 'Karangmulya');
insert into projects (title, color, city) values ('platea dictumst', 'Teal', 'Shuangshan');
insert into projects (title, color, city) values ('sit amet consectetuer', 'Mauv', 'Caen');
insert into projects (title, color, city) values ('varius', 'Khaki', 'Colcabamba');
insert into projects (title, color, city) values ('rutrum at lorem', 'Yellow', 'Włocławek');
insert into projects (title, color, city) values ('tempus vel pede', 'Green', 'Hamburg Bramfeld');
insert into projects (title, color, city) values ('ultrices', 'Purple', 'Pingtang');
insert into projects (title, color, city) values ('aliquet at', 'Yellow', 'Kunheda Woerzu Manzu');
insert into projects (title, color, city) values ('tortor', 'Purple', 'Zhovti Vody');
insert into projects (title, color, city) values ('orci luctus et', 'Red', 'Hanjianglu');
insert into projects (title, color, city) values ('erat nulla', 'Fuscia', 'Geoktschai');
insert into projects (title, color, city) values ('donec diam neque', 'Aquamarine', 'Konstantinovo');
insert into projects (title, color, city) values ('cras', 'Turquoise', 'Bonneuil-sur-Marne');
insert into projects (title, color, city) values ('purus eu', 'Orange', 'Saba Yoi');
insert into projects (title, color, city) values ('quis lectus', null, 'Tammela');
insert into projects (title, color, city) values ('non lectus aliquam', 'Orange', 'Madura');
insert into projects (title, color, city) values ('vulputate elementum nullam', 'Goldenrod', 'Thị Trấn Văn Quan');
insert into projects (title, color, city) values ('nunc', 'Teal', 'Jatisari');
insert into projects (title, color, city) values ('proin', 'Turquoise', 'St. Catharines');
insert into projects (title, color, city) values ('aliquet pulvinar sed', 'Fuscia', 'Krasna');
insert into projects (title, color, city) values ('sem duis', 'Violet', 'Nam Kliang');
insert into projects (title, color, city) values ('faucibus orci', 'Indigo', 'Wangcun');
insert into projects (title, color, city) values ('sociis natoque', 'Blue', 'Lansing');
insert into projects (title, color, city) values ('imperdiet', 'Teal', 'Al Ḩashwah');
insert into projects (title, color, city) values ('turpis enim blandit', 'Crimson', 'Carleton Place');
insert into projects (title, color, city) values ('fringilla rhoncus mauris', 'Purple', 'Vallauris');
insert into projects (title, color, city) values ('accumsan', 'Pink', 'Al Madīd');
insert into projects (title, color, city) values ('vivamus vel', 'Pink', 'Pskov');
insert into projects (title, color, city) values ('gravida sem praesent', 'Red', 'Chishtiān Mandi');
insert into projects (title, color, city) values ('in', 'Aquamarine', 'Levoberezhnaya');
insert into projects (title, color, city) values ('interdum', 'Khaki', 'Tall Tamr');
insert into projects (title, color, city) values ('commodo', 'Puce', 'Zala');
insert into projects (title, color, city) values ('amet consectetuer adipiscing', 'Goldenrod', 'Sokol');
insert into projects (title, color, city) values ('accumsan odio curabitur', 'Khaki', 'San Jose');
insert into projects (title, color, city) values ('venenatis', 'Maroon', 'Sydney Mines');
insert into projects (title, color, city) values ('porttitor pede', 'Blue', 'Dong Charoen');
insert into projects (title, color, city) values ('quam', 'Khaki', 'Kafr az Zayyāt');
insert into projects (title, color, city) values ('accumsan odio', 'Goldenrod', 'Khánh Hải');
insert into projects (title, color, city) values ('vel', 'Aquamarine', 'Kostyantynivka');
insert into projects (title, color, city) values ('pede lobortis ligula', 'Indigo', 'San Diego');
insert into projects (title, color, city) values ('urna', 'Pink', 'Songjiang');
insert into projects (title, color, city) values ('orci luctus', 'Indigo', 'Zaraza');
insert into projects (title, color, city) values ('turpis adipiscing', 'Goldenrod', 'Chumpi');
insert into projects (title, color, city) values ('primis', 'Crimson', 'Göteborg');
insert into projects (title, color, city) values ('nibh in', 'Fuscia', 'Kiltamagh');
insert into projects (title, color, city) values ('eu felis fusce', 'Khaki', 'Juripiranga');
insert into projects (title, color, city) values ('lectus', 'Red', 'Flores da Cunha');
insert into projects (title, color, city) values ('scelerisque quam', 'Green', 'Kebonan');
insert into projects (title, color, city) values ('vestibulum quam', 'Turquoise', 'Žabčice');
insert into projects (title, color, city) values ('eget', 'Indigo', 'Huntsville');
insert into projects (title, color, city) values ('vivamus', 'Yellow', 'Timrå');
insert into projects (title, color, city) values ('penatibus et magnis', 'Crimson', 'Valence');
insert into projects (title, color, city) values ('congue risus', 'Fuscia', 'Liugong');
insert into projects (title, color, city) values ('mauris vulputate elementum', 'Teal', 'Horní Bečva');
insert into projects (title, color, city) values ('dolor morbi', 'Khaki', 'Baranowo');
insert into projects (title, color, city) values ('amet lobortis sapien', 'Teal', 'Krasnofarfornyy');
insert into projects (title, color, city) values ('vulputate elementum', 'Maroon', 'Hetoudian');
insert into projects (title, color, city) values ('rhoncus', 'Indigo', 'Wiązownica');
insert into projects (title, color, city) values ('at turpis donec', 'Aquamarine', 'Aquiraz');
insert into projects (title, color, city) values ('eu massa', null, 'Dongsheng');
insert into projects (title, color, city) values ('pellentesque ultrices', 'Crimson', 'Borås');
insert into projects (title, color, city) values ('erat', null, 'Montasik');
insert into projects (title, color, city) values ('in', 'Blue', 'Macheke');
insert into projects (title, color, city) values ('sed nisl nunc', 'Red', 'Schaan');
insert into projects (title, color, city) values ('faucibus', null, 'Eséka');
insert into projects (title, color, city) values ('in faucibus', null, 'Buenavista');
insert into projects (title, color, city) values ('elit proin', 'Goldenrod', 'Nizhniy Kurkuzhin');
insert into projects (title, color, city) values ('pede malesuada', 'Red', 'Tagum');
insert into projects (title, color, city) values ('massa volutpat convallis', 'Blue', 'Tiaong');
insert into projects (title, color, city) values ('tortor', 'Red', 'Jiushe');
insert into projects (title, color, city) values ('dictumst maecenas ut', null, 'Nizhniy Kislyay');
insert into projects (title, color, city) values ('in leo', 'Aquamarine', 'Wootton');
insert into projects (title, color, city) values ('tellus', 'Maroon', 'Quba');
insert into projects (title, color, city) values ('mauris viverra diam', 'Fuscia', 'Guabito');
insert into projects (title, color, city) values ('rhoncus aliquet', 'Teal', 'Karangora');
insert into projects (title, color, city) values ('erat curabitur', 'Red', 'Carrigtwohill');
insert into projects (title, color, city) values ('ullamcorper augue a', 'Teal', 'Mari');
insert into projects (title, color, city) values ('mattis nibh', 'Pink', 'Babakanbungur');
insert into projects (title, color, city) values ('justo', 'Teal', 'Bairro Assunção Piedade');
insert into projects (title, color, city) values ('suspendisse', 'Turquoise', 'Vedène');
insert into projects (title, color, city) values ('commodo vulputate justo', 'Purple', 'Bull Savanna');
insert into projects (title, color, city) values ('pretium iaculis diam', 'Khaki', 'Xinfengjie');
insert into projects (title, color, city) values ('nulla suscipit ligula', 'Pink', 'Yenangyaung');
insert into projects (title, color, city) values ('nulla', 'Yellow', 'Dzaoudzi');
insert into projects (title, color, city) values ('sed', 'Indigo', 'Liantan');
insert into projects (title, color, city) values ('duis ac nibh', null, 'Wairiang');
insert into projects (title, color, city) values ('porttitor pede', 'Green', 'Daruoyan');
insert into projects (title, color, city) values ('sed vel enim', 'Puce', 'Cikembar');
insert into projects (title, color, city) values ('eu sapien', 'Mauv', 'Yisuhe');
insert into projects (title, color, city) values ('ornare', 'Goldenrod', 'Sui’an');
insert into projects (title, color, city) values ('curae mauris', 'Purple', 'Prostřední Bečva');
insert into projects (title, color, city) values ('cubilia curae nulla', 'Teal', 'Maguling');
insert into projects (title, color, city) values ('tempor', null, 'Tsant');
insert into projects (title, color, city) values ('odio condimentum id', 'Turquoise', 'Caxias');
insert into projects (title, color, city) values ('enim in', 'Blue', 'Napel');
insert into projects (title, color, city) values ('platea dictumst etiam', 'Orange', 'Sơn Trà');
insert into projects (title, color, city) values ('facilisi cras non', 'Goldenrod', 'Lunenburg');
insert into projects (title, color, city) values ('ultrices posuere cubilia', 'Khaki', 'Gusang');
insert into projects (title, color, city) values ('at feugiat', 'Khaki', 'Calumpang');
insert into projects (title, color, city) values ('quam', 'Blue', 'Rtyně v Podkrkonoší');
insert into projects (title, color, city) values ('luctus et ultrices', 'Red', 'Babana');
insert into projects (title, color, city) values ('tellus nulla', 'Khaki', 'Środa Wielkopolska');
insert into projects (title, color, city) values ('elementum in', 'Aquamarine', 'Oji River');
insert into projects (title, color, city) values ('nulla', 'Crimson', 'Cisaro');
insert into projects (title, color, city) values ('vehicula', null, 'Täby');
insert into projects (title, color, city) values ('aliquam augue quam', 'Mauv', 'Sorochuco');
insert into projects (title, color, city) values ('curae mauris', 'Yellow', 'Xiaxi');
insert into projects (title, color, city) values ('libero', 'Puce', 'Xinhe');
insert into projects (title, color, city) values ('iaculis', 'Mauv', 'Göteborg');
insert into projects (title, color, city) values ('amet nunc', 'Aquamarine', 'Medan');
insert into projects (title, color, city) values ('id ornare', 'Puce', 'Taurija');
insert into projects (title, color, city) values ('a odio in', 'Violet', 'San Felipe');
insert into projects (title, color, city) values ('diam', 'Pink', 'Besao');
insert into projects (title, color, city) values ('velit', null, 'Bykhaw');
insert into projects (title, color, city) values ('in faucibus orci', 'Aquamarine', 'Pyrzyce');
insert into projects (title, color, city) values ('ut', null, 'Olyshivka');
insert into projects (title, color, city) values ('hac', 'Pink', 'Karangdalam');
insert into projects (title, color, city) values ('amet eros', 'Puce', 'Bairro dos Marinheiros');
insert into projects (title, color, city) values ('dapibus', 'Teal', 'Monte Agudo');
insert into projects (title, color, city) values ('leo maecenas pulvinar', 'Pink', 'Beiguoyuan');
insert into projects (title, color, city) values ('maecenas rhoncus', 'Yellow', 'Muzidian');
insert into projects (title, color, city) values ('in libero ut', 'Fuscia', 'Deir Ḥannā');
insert into projects (title, color, city) values ('luctus et ultrices', 'Violet', 'Chai Nat');
insert into projects (title, color, city) values ('ridiculus mus', 'Purple', 'Zghartā');
insert into projects (title, color, city) values ('sem', 'Fuscia', 'Thành Phố Hạ Long');
insert into projects (title, color, city) values ('tempor', null, 'Songmuping');
insert into projects (title, color, city) values ('enim', 'Fuscia', 'Dadong');
insert into projects (title, color, city) values ('proin eu', 'Yellow', 'Polos');
insert into projects (title, color, city) values ('id ligula suspendisse', 'Blue', 'Bor Tungge');
insert into projects (title, color, city) values ('sapien', 'Turquoise', 'Saboyá');
insert into projects (title, color, city) values ('felis sed', 'Purple', 'Barajevo');
insert into projects (title, color, city) values ('purus sit amet', null, 'Jingxin');
insert into projects (title, color, city) values ('orci eget', 'Indigo', 'Jiangshan');
insert into projects (title, color, city) values ('iaculis congue', 'Turquoise', 'Dangbigih');
insert into projects (title, color, city) values ('rhoncus dui vel', 'Crimson', 'Youwei');
insert into projects (title, color, city) values ('elementum pellentesque quisque', 'Khaki', 'Jorok Dalam');
insert into projects (title, color, city) values ('nulla', 'Purple', 'Laoxialu');
insert into projects (title, color, city) values ('dapibus duis', 'Blue', 'Angao');
insert into projects (title, color, city) values ('amet sapien', 'Goldenrod', 'Cibunar');
insert into projects (title, color, city) values ('pretium iaculis diam', 'Turquoise', 'Tabālah');
insert into projects (title, color, city) values ('proin leo', 'Blue', 'Ji’an');
insert into projects (title, color, city) values ('etiam', 'Khaki', 'Wangcun');
insert into projects (title, color, city) values ('nibh', 'Aquamarine', 'Třebíč');
insert into projects (title, color, city) values ('pretium', 'Mauv', 'El Paso');
insert into projects (title, color, city) values ('ultrices', 'Aquamarine', 'Zaymishche');
insert into projects (title, color, city) values ('mi', 'Goldenrod', 'Mölndal');
insert into projects (title, color, city) values ('tellus in sagittis', null, 'Cateel');
insert into projects (title, color, city) values ('sapien sapien', 'Pink', 'Aībak');
insert into projects (title, color, city) values ('quam turpis', 'Indigo', 'Ábrego');
insert into projects (title, color, city) values ('pulvinar sed', 'Mauv', 'Gewanē');
insert into projects (title, color, city) values ('pede', 'Fuscia', 'Shijak');
insert into projects (title, color, city) values ('hac', 'Goldenrod', 'General Martín Miguel de Güemes');
insert into projects (title, color, city) values ('montes nascetur', 'Crimson', 'Kurashiki');
insert into projects (title, color, city) values ('nulla facilisi cras', 'Pink', 'Rudna Mała');
insert into projects (title, color, city) values ('mattis', null, 'Kökar');
insert into projects (title, color, city) values ('sapien', null, 'Magoúla');
insert into projects (title, color, city) values ('vel accumsan tellus', 'Teal', 'Guangfu');
insert into projects (title, color, city) values ('duis consequat', 'Puce', 'Makiyivka');
insert into projects (title, color, city) values ('nulla', null, 'Bébédja');
insert into projects (title, color, city) values ('nisi nam ultrices', 'Aquamarine', 'Karanganyar');
insert into projects (title, color, city) values ('nunc proin', 'Puce', 'Buenavista');
insert into projects (title, color, city) values ('tincidunt nulla', 'Purple', 'Thung Song');
insert into projects (title, color, city) values ('platea dictumst', 'Orange', 'Shu');
insert into projects (title, color, city) values ('in hac', 'Orange', 'Sabnova');
insert into projects (title, color, city) values ('ut nunc', 'Pink', 'Al Matūn');
insert into projects (title, color, city) values ('eu', 'Crimson', 'Limanancong');
insert into projects (title, color, city) values ('lacinia', 'Yellow', 'Fencheng');
insert into projects (title, color, city) values ('lectus pellentesque at', 'Violet', 'Béreldange');
insert into projects (title, color, city) values ('arcu sed augue', 'Maroon', 'Sobue');
insert into projects (title, color, city) values ('gravida sem', 'Orange', 'Kembangkerang Lauk Timur');
insert into projects (title, color, city) values ('donec ut', 'Puce', 'Hekou');
insert into projects (title, color, city) values ('volutpat', 'Goldenrod', 'Chatuchak');
insert into projects (title, color, city) values ('cursus urna ut', 'Red', 'Alis');
insert into projects (title, color, city) values ('suspendisse', 'Fuscia', 'Kwikila');
insert into projects (title, color, city) values ('eget', 'Red', 'Kazanlŭk');
insert into projects (title, color, city) values ('molestie', 'Teal', 'Doropayung');
insert into projects (title, color, city) values ('faucibus', 'Violet', 'Haifa');
insert into projects (title, color, city) values ('nisi', 'Puce', 'Forquilhinha');
insert into projects (title, color, city) values ('eu', 'Blue', 'Chame');
insert into projects (title, color, city) values ('maecenas tincidunt', 'Green', 'Yanwan');
insert into projects (title, color, city) values ('vel lectus in', 'Indigo', 'Beizhouzi');
insert into projects (title, color, city) values ('donec semper sapien', 'Orange', 'Labuan');
insert into projects (title, color, city) values ('mattis egestas metus', 'Khaki', 'Tantou');
insert into projects (title, color, city) values ('ligula suspendisse ornare', 'Green', 'Itaparica');
insert into projects (title, color, city) values ('quam', null, 'Bairro');
insert into projects (title, color, city) values ('enim', 'Pink', 'San Vicente');
insert into projects (title, color, city) values ('eros', 'Yellow', 'Lingzhi');
insert into projects (title, color, city) values ('convallis nunc', null, 'Beo');
insert into projects (title, color, city) values ('risus', 'Turquoise', 'Dicun');
insert into projects (title, color, city) values ('luctus tincidunt', 'Orange', 'Lesnikovo');
insert into projects (title, color, city) values ('phasellus id', 'Teal', 'Chvaletice');
insert into projects (title, color, city) values ('leo odio', 'Khaki', 'Jinquan');
insert into projects (title, color, city) values ('suspendisse', 'Fuscia', 'Nandayure');
insert into projects (title, color, city) values ('morbi vel', 'Maroon', 'Jiuxian');
insert into projects (title, color, city) values ('viverra dapibus', 'Fuscia', 'Marseille');
insert into projects (title, color, city) values ('ipsum dolor', 'Indigo', 'Hong’an Chengguanzhen');
insert into projects (title, color, city) values ('nisl nunc', 'Yellow', 'Liminka');
insert into projects (title, color, city) values ('in', 'Teal', 'Bulog');
insert into projects (title, color, city) values ('sapien varius', 'Goldenrod', 'Río Grande');
insert into projects (title, color, city) values ('cursus', 'Aquamarine', 'Shuanghe');
insert into projects (title, color, city) values ('sagittis dui vel', 'Fuscia', 'Xiongshan');
insert into projects (title, color, city) values ('arcu adipiscing', 'Maroon', 'Mulyadadi');
insert into projects (title, color, city) values ('eleifend pede', 'Fuscia', 'Utajärvi');
insert into projects (title, color, city) values ('curae mauris viverra', 'Mauv', 'Gore');
insert into projects (title, color, city) values ('vitae', 'Khaki', 'Krajan Kinanti');
insert into projects (title, color, city) values ('a', 'Red', 'Tubod');
insert into projects (title, color, city) values ('consectetuer adipiscing', null, 'Frederiksberg');
insert into projects (title, color, city) values ('aliquam sit', 'Khaki', 'Jindřichův Hradec');
insert into projects (title, color, city) values ('donec', 'Pink', 'Chenôve');
insert into projects (title, color, city) values ('iaculis justo', 'Orange', 'Gushui');
insert into projects (title, color, city) values ('quis lectus', 'Puce', 'Chortkiv');
insert into projects (title, color, city) values ('sem sed', 'Orange', 'Borek');
insert into projects (title, color, city) values ('vestibulum ante', 'Pink', 'Los Angeles');
insert into projects (title, color, city) values ('pede', null, 'Popovi');
insert into projects (title, color, city) values ('blandit ultrices', 'Turquoise', 'San Eugenio');
insert into projects (title, color, city) values ('amet', 'Turquoise', 'Calaya');
insert into projects (title, color, city) values ('habitasse platea', 'Khaki', 'Maloyaroslavets');
insert into projects (title, color, city) values ('a', 'Khaki', 'Hongqi');
insert into projects (title, color, city) values ('massa tempor convallis', 'Puce', 'Qazax');
insert into projects (title, color, city) values ('molestie', null, 'Feilaixia');
insert into projects (title, color, city) values ('sollicitudin ut', 'Maroon', 'Oetutulul');
insert into projects (title, color, city) values ('id', 'Khaki', 'Tetyushi');
insert into projects (title, color, city) values ('nulla', 'Teal', 'Rainis');
insert into projects (title, color, city) values ('eleifend luctus', 'Red', 'New York City');
insert into projects (title, color, city) values ('dapibus dolor vel', 'Purple', 'Laval');
insert into projects (title, color, city) values ('rutrum rutrum neque', null, 'Mounlapamôk');
insert into projects (title, color, city) values ('justo maecenas rhoncus', 'Maroon', 'Hushan');
insert into projects (title, color, city) values ('ut massa quis', null, 'Orlovskiy');
insert into projects (title, color, city) values ('commodo vulputate justo', 'Goldenrod', 'Tukuyu');
insert into projects (title, color, city) values ('ante', 'Puce', 'Chester');
insert into projects (title, color, city) values ('orci', 'Turquoise', 'Comodoro Rivadavia');
insert into projects (title, color, city) values ('nunc', 'Crimson', 'Novyy Urgal');
insert into projects (title, color, city) values ('pede', 'Violet', 'Thành Phố Hạ Long');
insert into projects (title, color, city) values ('felis', null, 'Issy-les-Moulineaux');
insert into projects (title, color, city) values ('massa', 'Aquamarine', 'Sandymount');
insert into projects (title, color, city) values ('libero nullam sit', 'Teal', 'Paratinga');
insert into projects (title, color, city) values ('turpis elementum', 'Aquamarine', 'Batojaran');
insert into projects (title, color, city) values ('elementum', 'Indigo', 'Uvarovka');
insert into projects (title, color, city) values ('orci', 'Green', 'Eschweiler');
insert into projects (title, color, city) values ('consequat', 'Maroon', 'Livramento');
insert into projects (title, color, city) values ('ac leo pellentesque', 'Indigo', 'Colorado Springs');
insert into projects (title, color, city) values ('quam pede lobortis', 'Teal', 'Wangmang');
insert into projects (title, color, city) values ('ante', 'Green', 'Oslo');
insert into projects (title, color, city) values ('eget', 'Turquoise', 'Zabaykal’sk');
insert into projects (title, color, city) values ('eu massa', 'Khaki', 'Goryachevodskiy');
insert into projects (title, color, city) values ('nisi vulputate nonummy', 'Fuscia', 'Custódia');
insert into projects (title, color, city) values ('pede', 'Blue', 'Bor');
insert into projects (title, color, city) values ('viverra diam vitae', 'Khaki', 'Jam');
insert into projects (title, color, city) values ('massa', 'Red', 'Morelos');
insert into projects (title, color, city) values ('dictumst', 'Aquamarine', 'Manta');
insert into projects (title, color, city) values ('erat fermentum justo', 'Red', 'Duofudu');
insert into projects (title, color, city) values ('non ligula', 'Fuscia', 'Mealhada');
insert into projects (title, color, city) values ('consequat dui', 'Puce', 'Igbo-Ukwu');
insert into projects (title, color, city) values ('accumsan tellus nisi', 'Indigo', 'Żelazków');
insert into projects (title, color, city) values ('elementum ligula vehicula', 'Indigo', 'Egvekinot');
insert into projects (title, color, city) values ('sagittis nam', 'Goldenrod', 'Tromsø');
insert into projects (title, color, city) values ('lacus at turpis', 'Crimson', 'Manturovo');
insert into projects (title, color, city) values ('curae nulla dapibus', 'Green', 'Pimian');
insert into projects (title, color, city) values ('odio', 'Green', 'Leninogorsk');
insert into projects (title, color, city) values ('eget', 'Teal', 'Al ‘Ulá');
insert into projects (title, color, city) values ('nulla', 'Red', 'Dengyue');
insert into projects (title, color, city) values ('mollis', 'Green', 'Colegiales');
insert into projects (title, color, city) values ('dolor sit', 'Teal', 'Dundrum');
insert into projects (title, color, city) values ('lacinia sapien quis', 'Green', 'Baixo Guandu');
insert into projects (title, color, city) values ('nullam porttitor lacus', 'Violet', 'Kasreman');
insert into projects (title, color, city) values ('sed sagittis', 'Mauv', 'Ruda Śląska');
insert into projects (title, color, city) values ('consequat', 'Mauv', 'Enköping');
insert into projects (title, color, city) values ('congue etiam justo', null, 'Clogherhead');
insert into projects (title, color, city) values ('aliquet', 'Indigo', 'Foumbouni');
insert into projects (title, color, city) values ('imperdiet', 'Teal', 'Mesopotamía');
insert into projects (title, color, city) values ('diam nam tristique', 'Indigo', 'Dahuangwei');
insert into projects (title, color, city) values ('nulla integer', 'Red', 'Brotas');
insert into projects (title, color, city) values ('ante ipsum primis', 'Fuscia', 'Meylan');
insert into projects (title, color, city) values ('eleifend', 'Crimson', 'Sanhe');
insert into projects (title, color, city) values ('vel enim', 'Fuscia', 'Banjar Dharmasemedi');
insert into projects (title, color, city) values ('tincidunt', null, 'Moyynkum');
insert into projects (title, color, city) values ('nisl', 'Pink', 'Simpanganduwet');
insert into projects (title, color, city) values ('pellentesque volutpat dui', 'Indigo', 'Oslo');
insert into projects (title, color, city) values ('ornare consequat', 'Turquoise', 'Paris La Défense');
insert into projects (title, color, city) values ('ante', 'Aquamarine', 'Aş Şanamayn');
insert into projects (title, color, city) values ('a suscipit nulla', 'Purple', 'Guanban');
insert into projects (title, color, city) values ('consequat lectus in', 'Blue', 'Chai Nat');
insert into projects (title, color, city) values ('sit amet', 'Blue', 'Independencia');
insert into projects (title, color, city) values ('proin', 'Yellow', 'Oetutulul');
insert into projects (title, color, city) values ('rhoncus aliquet', 'Aquamarine', 'Paola');
insert into projects (title, color, city) values ('massa quis augue', 'Teal', 'Presidente Médici');
insert into projects (title, color, city) values ('tempus vivamus', null, 'Butare');
insert into projects (title, color, city) values ('aenean sit amet', 'Fuscia', 'Bayog');
insert into projects (title, color, city) values ('natoque penatibus et', 'Maroon', 'Kroczyce');
insert into projects (title, color, city) values ('nisi volutpat', 'Pink', 'Fier-Çifçi');
insert into projects (title, color, city) values ('eu orci', 'Fuscia', 'Baishui');
insert into projects (title, color, city) values ('suspendisse potenti in', 'Orange', 'Santana do Paraíso');
insert into projects (title, color, city) values ('vivamus metus arcu', 'Aquamarine', 'Persen');
insert into projects (title, color, city) values ('morbi vel', 'Blue', 'Kolor');
insert into projects (title, color, city) values ('pellentesque volutpat dui', 'Fuscia', 'Eastern Suburbs Mc');
insert into projects (title, color, city) values ('eget', 'Goldenrod', 'Yongjiu');
insert into projects (title, color, city) values ('lacus purus aliquet', 'Turquoise', 'Vladimirskaya');
insert into projects (title, color, city) values ('dapibus at', 'Green', 'Tayturka');
insert into projects (title, color, city) values ('a odio', 'Mauv', 'Piketberg');
insert into projects (title, color, city) values ('tortor', null, 'Batagay-Alyta');
insert into projects (title, color, city) values ('elementum eu interdum', 'Blue', 'Vaxholm');
insert into projects (title, color, city) values ('nulla sed', 'Violet', 'Musina');
insert into projects (title, color, city) values ('scelerisque', 'Turquoise', 'Afanas’yeva');
insert into projects (title, color, city) values ('tincidunt', 'Teal', 'Sarmanovo');
insert into projects (title, color, city) values ('orci vehicula condimentum', 'Yellow', 'Donghai');
insert into projects (title, color, city) values ('accumsan tellus', 'Maroon', 'Waldbredimus');
insert into projects (title, color, city) values ('augue vestibulum ante', 'Violet', 'Nāḩīyat Saddat al Hindīyah');
insert into projects (title, color, city) values ('sem mauris laoreet', 'Purple', 'Zishan');
insert into projects (title, color, city) values ('aenean', 'Fuscia', 'Smimou');
insert into projects (title, color, city) values ('nulla integer', 'Aquamarine', 'Houxi');
insert into projects (title, color, city) values ('nullam sit amet', 'Crimson', 'Jiangkou');
insert into projects (title, color, city) values ('aliquam', null, 'Yukhnov');
insert into projects (title, color, city) values ('adipiscing elit', 'Goldenrod', 'Nioki');
insert into projects (title, color, city) values ('ut suscipit a', 'Aquamarine', 'Meilisi');
insert into projects (title, color, city) values ('pede lobortis', 'Khaki', 'Lianfa');
insert into projects (title, color, city) values ('ac neque duis', 'Teal', 'Habiganj');
insert into projects (title, color, city) values ('mauris lacinia', 'Puce', 'Lyublino');
insert into projects (title, color, city) values ('habitasse platea dictumst', 'Turquoise', 'Arlington');
insert into projects (title, color, city) values ('mi pede', 'Violet', 'Mafeteng');
insert into projects (title, color, city) values ('ut', 'Crimson', 'Mariano Moreno');
insert into projects (title, color, city) values ('sed ante vivamus', 'Fuscia', 'Xuji');
insert into projects (title, color, city) values ('tincidunt lacus', 'Purple', 'Saint John’s');
insert into projects (title, color, city) values ('aliquam', 'Teal', 'Iida');
insert into projects (title, color, city) values ('odio odio', 'Puce', 'Jincun');
insert into projects (title, color, city) values ('non mi integer', null, 'San Mariano');
insert into projects (title, color, city) values ('donec', 'Mauv', 'Xinglong');
insert into projects (title, color, city) values ('at', 'Aquamarine', 'Feteira Grande');
insert into projects (title, color, city) values ('vel', 'Puce', 'Sundsvall');
insert into projects (title, color, city) values ('ipsum', 'Purple', 'Benešov nad Černou');
insert into projects (title, color, city) values ('felis ut', 'Maroon', 'Oelaba');
insert into projects (title, color, city) values ('enim leo', 'Yellow', 'El Bálsamo');
insert into projects (title, color, city) values ('ac tellus', 'Puce', 'Cilated');
insert into projects (title, color, city) values ('primis in faucibus', 'Blue', 'Huangma');
insert into projects (title, color, city) values ('sit', 'Khaki', 'Tzaneen');
insert into projects (title, color, city) values ('adipiscing lorem', null, 'Cigadog');
insert into projects (title, color, city) values ('hendrerit at', null, 'Katsikás');
insert into projects (title, color, city) values ('phasellus', 'Khaki', 'Boco');
insert into projects (title, color, city) values ('diam erat', 'Orange', 'Göteborg');
insert into projects (title, color, city) values ('sed vestibulum', 'Pink', 'Ruchihe');
insert into projects (title, color, city) values ('diam cras pellentesque', 'Teal', 'Enhe Hada');
insert into projects (title, color, city) values ('eget elit sodales', 'Turquoise', 'Praingkareha');
insert into projects (title, color, city) values ('ante', null, 'Bandarbeyla');
insert into projects (title, color, city) values ('vivamus', 'Red', 'Apitong');
insert into projects (title, color, city) values ('in', 'Red', 'Izobil’nyy');
insert into projects (title, color, city) values ('in felis eu', 'Puce', 'Taber');
insert into projects (title, color, city) values ('ultrices vel augue', 'Violet', 'Rajadesa');
insert into projects (title, color, city) values ('hendrerit at', 'Pink', 'Presidente Prudente');
insert into projects (title, color, city) values ('sociis natoque penatibus', 'Maroon', 'Saint Petersburg');
insert into projects (title, color, city) values ('morbi odio', 'Indigo', 'Grabovci');
insert into projects (title, color, city) values ('mus', 'Green', 'Saint-Sauveur');
insert into projects (title, color, city) values ('posuere', 'Fuscia', 'Jiangchi');
insert into projects (title, color, city) values ('mauris vulputate elementum', 'Crimson', 'Mashi');
insert into projects (title, color, city) values ('vestibulum', 'Orange', 'Courtaboeuf');
insert into projects (title, color, city) values ('sapien non mi', 'Maroon', 'Hällefors');
insert into projects (title, color, city) values ('ac', 'Purple', 'Foso');
insert into projects (title, color, city) values ('id turpis', 'Goldenrod', 'Laoxingchang');
insert into projects (title, color, city) values ('semper porta', 'Aquamarine', 'Ramadi');
insert into projects (title, color, city) values ('quis lectus', 'Yellow', 'Mirontsi');
insert into projects (title, color, city) values ('consequat nulla nisl', null, 'Gerong');
insert into projects (title, color, city) values ('ut', 'Blue', 'Mondokan');
insert into projects (title, color, city) values ('lobortis', 'Turquoise', 'Uchkeken');
insert into projects (title, color, city) values ('sit amet', 'Indigo', 'Paciran');
insert into projects (title, color, city) values ('tristique', 'Violet', 'Jakšić');
insert into projects (title, color, city) values ('lorem', null, 'Inđija');
insert into projects (title, color, city) values ('tristique in tempus', 'Pink', 'Kamaris');
insert into projects (title, color, city) values ('integer', 'Orange', 'Changxi');
insert into projects (title, color, city) values ('sit', 'Khaki', 'Uruguaiana');
insert into projects (title, color, city) values ('vestibulum', 'Blue', 'Angren');
insert into projects (title, color, city) values ('interdum', 'Orange', 'Winneba');
insert into projects (title, color, city) values ('mauris enim', 'Blue', 'Zbąszyń');
insert into projects (title, color, city) values ('tempus', 'Maroon', 'Huanghua');
insert into projects (title, color, city) values ('molestie hendrerit at', 'Teal', 'Tunasbaru');
insert into projects (title, color, city) values ('pharetra magna ac', 'Blue', 'Rondonópolis');
insert into projects (title, color, city) values ('magnis dis', null, 'Ljubuški');
insert into projects (title, color, city) values ('in faucibus orci', 'Green', 'Serang');
insert into projects (title, color, city) values ('justo nec', 'Teal', 'Vir');
insert into projects (title, color, city) values ('tristique in', 'Maroon', 'Xinshi');
insert into projects (title, color, city) values ('turpis', 'Violet', 'Delicias');
insert into projects (title, color, city) values ('nulla', 'Indigo', '‘Alāqahdārī Gēlān');
insert into projects (title, color, city) values ('aenean sit amet', null, 'São Luiz Gonzaga');
insert into projects (title, color, city) values ('libero', null, 'Namasuba');
insert into projects (title, color, city) values ('augue', null, 'Azua');
insert into projects (title, color, city) values ('quisque ut', 'Goldenrod', 'Liuhou');
insert into projects (title, color, city) values ('ligula', 'Maroon', 'Teresa');
insert into projects (title, color, city) values ('elementum eu', 'Teal', 'Artesianón');
