create table projects (
	id SERIAL PRIMARY KEY,
	title TEXT,
	color VARCHAR(50),
	city VARCHAR(50)
);
insert into projects (id, title, color, city) values (1, 'est phasellus sit', 'Orange', 'Chaumont');
insert into projects (id, title, color, city) values (2, 'augue vel accumsan', null, 'Chojnice');
insert into projects (id, title, color, city) values (3, 'ridiculus', 'Purple', 'Ngou');
insert into projects (id, title, color, city) values (4, 'curae mauris', 'Pink', 'Mets Parni');
insert into projects (id, title, color, city) values (5, 'eu pede', 'Teal', 'Alingsås');
insert into projects (id, title, color, city) values (6, 'cursus id turpis', 'Fuscia', 'Rauma');
insert into projects (id, title, color, city) values (7, 'tempor', 'Crimson', 'Chumpi');
insert into projects (id, title, color, city) values (8, 'vulputate', 'Crimson', 'Banraeaba Village');
insert into projects (id, title, color, city) values (9, 'tellus nisi eu', null, 'Mari');
insert into projects (id, title, color, city) values (10, 'fermentum donec ut', 'Pink', 'Pemba');
insert into projects (id, title, color, city) values (11, 'sapien cum sociis', 'Goldenrod', 'Ntobo');
insert into projects (id, title, color, city) values (12, 'sapien', 'Blue', 'Białobrzegi');
insert into projects (id, title, color, city) values (13, 'mauris lacinia', 'Puce', 'Tunggulsari');
insert into projects (id, title, color, city) values (14, 'non sodales sed', 'Khaki', 'Shambu');
insert into projects (id, title, color, city) values (15, 'massa', 'Red', 'Mölndal');
insert into projects (id, title, color, city) values (16, 'leo odio', null, 'Psebay');
insert into projects (id, title, color, city) values (17, 'sit', 'Green', 'Yeliguan');
insert into projects (id, title, color, city) values (18, 'augue vestibulum ante', 'Red', 'Magay');
insert into projects (id, title, color, city) values (19, 'enim lorem ipsum', 'Pink', 'Praia de Mira');
insert into projects (id, title, color, city) values (20, 'in sapien iaculis', 'Pink', 'Liqi');
insert into projects (id, title, color, city) values (21, 'porta volutpat', null, 'Can-Avid');
insert into projects (id, title, color, city) values (22, 'aenean', 'Yellow', 'Bakov nad Jizerou');
insert into projects (id, title, color, city) values (23, 'dolor quis odio', 'Goldenrod', 'Chone');
insert into projects (id, title, color, city) values (24, 'quis orci', 'Indigo', 'Fucun');
insert into projects (id, title, color, city) values (25, 'parturient montes nascetur', 'Turquoise', 'Bulls');
insert into projects (id, title, color, city) values (26, 'porta', 'Aquamarine', 'Lagoa');
insert into projects (id, title, color, city) values (27, 'fringilla rhoncus mauris', 'Indigo', 'Ilha Solteira');
insert into projects (id, title, color, city) values (28, 'mattis nibh', 'Khaki', 'Vitry-le-François');
insert into projects (id, title, color, city) values (29, 'diam id', 'Goldenrod', 'Pontevedra');
insert into projects (id, title, color, city) values (30, 'lobortis convallis', 'Pink', 'Wukari');
insert into projects (id, title, color, city) values (31, 'placerat ante nulla', 'Fuscia', 'Xinó Neró');
insert into projects (id, title, color, city) values (32, 'non ligula pellentesque', 'Red', 'Kajiki');
insert into projects (id, title, color, city) values (33, 'sagittis', 'Turquoise', 'Kalloní');
insert into projects (id, title, color, city) values (34, 'suspendisse accumsan tortor', 'Purple', 'Lloqan');
insert into projects (id, title, color, city) values (35, 'phasellus in', null, 'Benchu');
insert into projects (id, title, color, city) values (36, 'laoreet ut rhoncus', null, 'Itaporanga');
insert into projects (id, title, color, city) values (37, 'vestibulum', 'Yellow', 'Zhuyeping');
insert into projects (id, title, color, city) values (38, 'ultrices enim', 'Goldenrod', 'San Juan de la Maguana');
insert into projects (id, title, color, city) values (39, 'id', 'Maroon', 'Stari Banovci');
insert into projects (id, title, color, city) values (40, 'eget semper', 'Pink', 'Krajan Karangwage');
insert into projects (id, title, color, city) values (41, 'blandit lacinia', 'Indigo', 'Zhuyu');
insert into projects (id, title, color, city) values (42, 'a', 'Yellow', 'Yuyue');
insert into projects (id, title, color, city) values (43, 'nisi venenatis tristique', 'Khaki', 'Laojie');
insert into projects (id, title, color, city) values (44, 'tincidunt lacus at', 'Red', 'Betafo');
insert into projects (id, title, color, city) values (45, 'turpis', 'Violet', 'Pokrovskoye-Streshnëvo');
insert into projects (id, title, color, city) values (46, 'maecenas', 'Aquamarine', 'Comalapa');
insert into projects (id, title, color, city) values (47, 'ante', 'Aquamarine', 'Criciúma');
insert into projects (id, title, color, city) values (48, 'nulla quisque', null, 'Vila Nova de Gaia');
insert into projects (id, title, color, city) values (49, 'maecenas tincidunt', 'Purple', 'Fuhai');
insert into projects (id, title, color, city) values (50, 'blandit nam', 'Green', 'Oborniki Śląskie');
insert into projects (id, title, color, city) values (51, 'tincidunt', 'Yellow', 'Xinzhou');
insert into projects (id, title, color, city) values (52, 'aliquam lacus morbi', null, 'Melbourne');
insert into projects (id, title, color, city) values (53, 'felis donec semper', 'Purple', 'Van Nuys');
insert into projects (id, title, color, city) values (54, 'curabitur gravida', 'Goldenrod', 'Trondheim');
insert into projects (id, title, color, city) values (55, 'dapibus augue', 'Goldenrod', 'Hanggan');
insert into projects (id, title, color, city) values (56, 'eget orci', 'Turquoise', 'Jinping');
insert into projects (id, title, color, city) values (57, 'quam sapien', 'Orange', 'Jäppilä');
insert into projects (id, title, color, city) values (58, 'lobortis convallis', 'Crimson', 'Manaus');
insert into projects (id, title, color, city) values (59, 'donec', 'Green', 'La Huerta');
insert into projects (id, title, color, city) values (60, 'est', 'Khaki', 'Jiaoxie');
insert into projects (id, title, color, city) values (61, 'at', 'Green', 'Áyioi Apóstoloi');
insert into projects (id, title, color, city) values (62, 'felis eu', 'Purple', 'Independencia');
insert into projects (id, title, color, city) values (63, 'ac', 'Khaki', 'Zdounky');
insert into projects (id, title, color, city) values (64, 'congue etiam', 'Mauv', 'Kazanskoye');
insert into projects (id, title, color, city) values (65, 'consequat varius integer', 'Indigo', 'Huangzhuang');
insert into projects (id, title, color, city) values (66, 'odio curabitur convallis', 'Red', 'Karakabak');
insert into projects (id, title, color, city) values (67, 'nonummy integer non', 'Puce', 'Cabadiangan');
insert into projects (id, title, color, city) values (68, 'massa volutpat', null, 'Itajaí');
insert into projects (id, title, color, city) values (69, 'odio', 'Red', 'Erie');
insert into projects (id, title, color, city) values (70, 'pede', 'Red', 'Chojnów');
insert into projects (id, title, color, city) values (71, 'parturient', 'Crimson', 'Xinshi');
insert into projects (id, title, color, city) values (72, 'mauris sit amet', 'Crimson', 'Marcabal');
insert into projects (id, title, color, city) values (73, 'est et', 'Purple', 'Sendung');
insert into projects (id, title, color, city) values (74, 'platea dictumst etiam', 'Red', 'Angra do Heroísmo');
insert into projects (id, title, color, city) values (75, 'elit', 'Turquoise', 'Gorgoram');
insert into projects (id, title, color, city) values (76, 'amet consectetuer', 'Purple', 'Chibuto');
insert into projects (id, title, color, city) values (77, 'vel nulla', 'Yellow', 'Huanggu');
insert into projects (id, title, color, city) values (78, 'in sapien', 'Blue', 'Donskoye');
insert into projects (id, title, color, city) values (79, 'elementum in hac', 'Turquoise', 'Pasirlaja');
insert into projects (id, title, color, city) values (80, 'aliquet', 'Teal', 'Saint Joseph');
insert into projects (id, title, color, city) values (81, 'massa donec dapibus', 'Green', 'Tigaherang');
insert into projects (id, title, color, city) values (82, 'interdum', 'Pink', 'København');
insert into projects (id, title, color, city) values (83, 'curae donec pharetra', null, 'Taipingying');
insert into projects (id, title, color, city) values (84, 'hac habitasse', 'Violet', 'Chơn Thành');
insert into projects (id, title, color, city) values (85, 'arcu', null, 'Qixian');
insert into projects (id, title, color, city) values (86, 'luctus', 'Purple', 'Stockholm');
insert into projects (id, title, color, city) values (87, 'est', 'Blue', 'Bronx');
insert into projects (id, title, color, city) values (88, 'iaculis', 'Indigo', 'Shums’k');
insert into projects (id, title, color, city) values (89, 'ipsum dolor', 'Orange', 'Temirtau');
insert into projects (id, title, color, city) values (90, 'vel', 'Khaki', 'Gornyye Klyuchi');
insert into projects (id, title, color, city) values (91, 'maecenas', 'Aquamarine', 'Cambará');
insert into projects (id, title, color, city) values (92, 'molestie hendrerit', 'Yellow', 'Quy Đạt');
insert into projects (id, title, color, city) values (93, 'velit donec diam', 'Teal', 'Fort Worth');
insert into projects (id, title, color, city) values (94, 'blandit lacinia', 'Aquamarine', 'Chikwawa');
insert into projects (id, title, color, city) values (95, 'nam nulla', null, 'Ježdovec');
insert into projects (id, title, color, city) values (96, 'sed accumsan', 'Red', 'Apodi');
insert into projects (id, title, color, city) values (97, 'mi', null, 'Chumikan');
insert into projects (id, title, color, city) values (98, 'lobortis sapien', null, 'Lambangan Kulon');
insert into projects (id, title, color, city) values (99, 'vitae ipsum', 'Fuscia', 'Nuamuzi');
insert into projects (id, title, color, city) values (100, 'odio elementum', 'Crimson', 'San José');
insert into projects (id, title, color, city) values (101, 'ante vestibulum', 'Pink', 'Sicaya');
insert into projects (id, title, color, city) values (102, 'hac habitasse', 'Pink', 'Haebaru');
insert into projects (id, title, color, city) values (103, 'convallis eget', null, 'El Paso');
insert into projects (id, title, color, city) values (104, 'imperdiet sapien', 'Green', 'Zouparria do Monte');
insert into projects (id, title, color, city) values (105, 'eu interdum eu', 'Pink', 'Blois');
insert into projects (id, title, color, city) values (106, 'faucibus orci', 'Turquoise', 'Tianxingchang');
insert into projects (id, title, color, city) values (107, 'rutrum', null, 'Tarutung');
insert into projects (id, title, color, city) values (108, 'vulputate', 'Orange', 'Malamig');
insert into projects (id, title, color, city) values (109, 'tortor', null, 'Puente Nacional');
insert into projects (id, title, color, city) values (110, 'quisque', 'Yellow', 'Cihambali');
insert into projects (id, title, color, city) values (111, 'amet consectetuer adipiscing', 'Red', 'Szczawnica');
insert into projects (id, title, color, city) values (112, 'ipsum primis in', 'Purple', 'Tabio');
insert into projects (id, title, color, city) values (113, 'in hac', 'Mauv', 'Tangtou');
insert into projects (id, title, color, city) values (114, 'vestibulum ante ipsum', 'Red', 'Xunjian');
insert into projects (id, title, color, city) values (115, 'magna', 'Blue', 'Vydreno');
insert into projects (id, title, color, city) values (116, 'eget massa', 'Green', 'Caimitillo');
insert into projects (id, title, color, city) values (117, 'ligula nec sem', null, 'Wangon');
insert into projects (id, title, color, city) values (118, 'dui vel', 'Pink', 'Ichnya');
insert into projects (id, title, color, city) values (119, 'quisque arcu', 'Orange', 'Ganghwa-gun');
insert into projects (id, title, color, city) values (120, 'non', 'Orange', 'San Isidro');
insert into projects (id, title, color, city) values (121, 'phasellus in felis', 'Red', 'Pogorzyce');
insert into projects (id, title, color, city) values (122, 'habitasse platea', null, 'Pederneiras');
insert into projects (id, title, color, city) values (123, 'pulvinar lobortis est', 'Violet', 'Pontevedra');
insert into projects (id, title, color, city) values (124, 'et', 'Fuscia', 'Tarnowskie Góry');
insert into projects (id, title, color, city) values (125, 'nulla elit', 'Puce', 'Batulawang');
insert into projects (id, title, color, city) values (126, 'lorem id ligula', 'Turquoise', 'Boucinhas');
insert into projects (id, title, color, city) values (127, 'consequat ut nulla', 'Orange', 'Masons Bay');
insert into projects (id, title, color, city) values (128, 'cubilia curae mauris', 'Turquoise', 'Estacion');
insert into projects (id, title, color, city) values (129, 'eros viverra eget', 'Orange', 'Mawlaik');
insert into projects (id, title, color, city) values (130, 'convallis', 'Maroon', 'Svetlyy Yar');
insert into projects (id, title, color, city) values (131, 'volutpat erat quisque', 'Goldenrod', 'Saraktash');
insert into projects (id, title, color, city) values (132, 'suscipit ligula', 'Fuscia', 'Strängnäs');
insert into projects (id, title, color, city) values (133, 'nullam orci pede', 'Fuscia', 'Huangzhu');
insert into projects (id, title, color, city) values (134, 'eget', 'Violet', 'Sahagún');
insert into projects (id, title, color, city) values (135, 'vestibulum', 'Red', 'Hamakita');
insert into projects (id, title, color, city) values (136, 'adipiscing lorem vitae', 'Crimson', 'Nggesa');
insert into projects (id, title, color, city) values (137, 'morbi sem mauris', null, 'Saginaw');
insert into projects (id, title, color, city) values (138, 'id mauris', 'Violet', 'Odiongan');
insert into projects (id, title, color, city) values (139, 'erat', 'Teal', 'Khŭjand');
insert into projects (id, title, color, city) values (140, 'vestibulum aliquet ultrices', 'Khaki', 'Las Vegas');
insert into projects (id, title, color, city) values (141, 'amet cursus', 'Green', 'Nakhon Luang');
insert into projects (id, title, color, city) values (142, 'pharetra magna', 'Mauv', 'Presidente Epitácio');
insert into projects (id, title, color, city) values (143, 'etiam pretium', 'Maroon', 'São Pedro de Trafaria');
insert into projects (id, title, color, city) values (144, 'potenti', 'Maroon', 'Hexi');
insert into projects (id, title, color, city) values (145, 'congue eget semper', 'Teal', 'Khyzy');
insert into projects (id, title, color, city) values (146, 'rhoncus', 'Red', 'Villa Ascasubi');
insert into projects (id, title, color, city) values (147, 'magna at nunc', null, 'Doāba');
insert into projects (id, title, color, city) values (148, 'tempus vivamus in', 'Fuscia', 'Nizwá');
insert into projects (id, title, color, city) values (149, 'justo in', 'Goldenrod', 'Changting');
insert into projects (id, title, color, city) values (150, 'rutrum at lorem', 'Fuscia', 'Sucre');
insert into projects (id, title, color, city) values (151, 'penatibus et', 'Khaki', 'Quintãs');
insert into projects (id, title, color, city) values (152, 'vestibulum', 'Indigo', 'Sungai Raya');
insert into projects (id, title, color, city) values (153, 'nisl nunc', 'Indigo', 'Zyukayka');
insert into projects (id, title, color, city) values (154, 'quisque arcu', 'Turquoise', 'Imsida');
insert into projects (id, title, color, city) values (155, 'justo', 'Violet', 'Letlhakeng');
insert into projects (id, title, color, city) values (156, 'ut blandit', 'Teal', 'Jugezhuang');
insert into projects (id, title, color, city) values (157, 'nulla mollis', 'Yellow', 'Nanyi');
insert into projects (id, title, color, city) values (158, 'sollicitudin vitae consectetuer', 'Orange', 'La Roche-sur-Yon');
insert into projects (id, title, color, city) values (159, 'semper sapien a', 'Green', 'Zhongxian');
insert into projects (id, title, color, city) values (160, 'amet justo', 'Maroon', 'Altamira');
insert into projects (id, title, color, city) values (161, 'tristique in', 'Green', 'Sredno Konjare');
insert into projects (id, title, color, city) values (162, 'primis in', null, 'Hōfu');
insert into projects (id, title, color, city) values (163, 'consequat', 'Khaki', 'La Peña');
insert into projects (id, title, color, city) values (164, 'accumsan felis', 'Teal', 'Babakanloa');
insert into projects (id, title, color, city) values (165, 'varius nulla', null, 'České Meziříčí');
insert into projects (id, title, color, city) values (166, 'sit amet', 'Turquoise', 'Milanów');
insert into projects (id, title, color, city) values (167, 'pellentesque eget', 'Maroon', 'Batawa');
insert into projects (id, title, color, city) values (168, 'luctus et ultrices', 'Maroon', 'Springfield');
insert into projects (id, title, color, city) values (169, 'iaculis congue vivamus', 'Indigo', 'Lop Buri');
insert into projects (id, title, color, city) values (170, 'augue vel accumsan', 'Khaki', 'Fuzihe');
insert into projects (id, title, color, city) values (171, 'id massa id', 'Indigo', 'Cabricán');
insert into projects (id, title, color, city) values (172, 'integer tincidunt ante', 'Mauv', 'Mengla');
insert into projects (id, title, color, city) values (173, 'rhoncus', 'Mauv', 'Ciomas');
insert into projects (id, title, color, city) values (174, 'vel augue', 'Mauv', 'Zemun');
insert into projects (id, title, color, city) values (175, 'magna', 'Pink', 'Sundsvall');
insert into projects (id, title, color, city) values (176, 'est', 'Fuscia', 'Dukuhbadag');
insert into projects (id, title, color, city) values (177, 'proin interdum', 'Indigo', 'Phaya Thai');
insert into projects (id, title, color, city) values (178, 'donec diam neque', 'Mauv', 'San Jose');
insert into projects (id, title, color, city) values (179, 'cum', 'Mauv', 'Kahabe');
insert into projects (id, title, color, city) values (180, 'vel', null, 'Garden Grove');
insert into projects (id, title, color, city) values (181, 'blandit mi', 'Fuscia', 'Jangkat');
insert into projects (id, title, color, city) values (182, 'nulla ac', 'Purple', 'Marne-la-Vallée');
insert into projects (id, title, color, city) values (183, 'vestibulum proin', 'Yellow', 'Horokhiv');
insert into projects (id, title, color, city) values (184, 'nonummy maecenas', 'Orange', 'Baganha');
insert into projects (id, title, color, city) values (185, 'in sapien', 'Indigo', 'Waeng Yai');
insert into projects (id, title, color, city) values (186, 'orci luctus et', 'Blue', 'Lanos');
insert into projects (id, title, color, city) values (187, 'integer pede justo', 'Fuscia', 'Mairinque');
insert into projects (id, title, color, city) values (188, 'justo', 'Pink', 'New Haven');
insert into projects (id, title, color, city) values (189, 'hac habitasse platea', 'Goldenrod', 'Hongqi');
insert into projects (id, title, color, city) values (190, 'tempus vivamus', 'Khaki', 'Shūkat aş Şūfī');
insert into projects (id, title, color, city) values (191, 'praesent', 'Teal', 'Puerto López');
insert into projects (id, title, color, city) values (192, 'est', 'Goldenrod', 'Ráječko');
insert into projects (id, title, color, city) values (193, 'luctus', 'Purple', 'Sanhe');
insert into projects (id, title, color, city) values (194, 'neque sapien placerat', 'Maroon', 'Kallar Kahār');
insert into projects (id, title, color, city) values (195, 'gravida sem', 'Turquoise', 'Kubang');
insert into projects (id, title, color, city) values (196, 'cursus urna', null, 'Xiejiaya');
insert into projects (id, title, color, city) values (197, 'erat id mauris', 'Mauv', 'Guaiúba');
insert into projects (id, title, color, city) values (198, 'amet consectetuer', 'Turquoise', 'Arjona');
insert into projects (id, title, color, city) values (199, 'at nulla suspendisse', 'Pink', 'Gereneng');
insert into projects (id, title, color, city) values (200, 'tellus nulla ut', 'Fuscia', 'Cigembor');
insert into projects (id, title, color, city) values (201, 'luctus ultricies', 'Aquamarine', 'Meshcherino');
insert into projects (id, title, color, city) values (202, 'sollicitudin ut suscipit', 'Aquamarine', 'Ushuaia');
insert into projects (id, title, color, city) values (203, 'pretium', null, 'Barberena');
insert into projects (id, title, color, city) values (204, 'justo nec condimentum', 'Puce', 'Vila Chã');
insert into projects (id, title, color, city) values (205, 'ultrices mattis', 'Green', 'Baihe');
insert into projects (id, title, color, city) values (206, 'tempus vel', 'Fuscia', 'Jimeta');
insert into projects (id, title, color, city) values (207, 'rhoncus dui', 'Red', 'Sa Kaeo');
insert into projects (id, title, color, city) values (208, 'suspendisse potenti cras', 'Blue', 'Maralal');
insert into projects (id, title, color, city) values (209, 'eros', 'Puce', 'Granada');
insert into projects (id, title, color, city) values (210, 'quis justo maecenas', 'Turquoise', 'Tene');
insert into projects (id, title, color, city) values (211, 'tempor', 'Khaki', 'Tržič');
insert into projects (id, title, color, city) values (212, 'habitasse platea', 'Turquoise', 'Ares Tengah');
insert into projects (id, title, color, city) values (213, 'mauris', 'Indigo', 'Sablé-sur-Sarthe');
insert into projects (id, title, color, city) values (214, 'duis bibendum morbi', 'Violet', 'Shuanglu');
insert into projects (id, title, color, city) values (215, 'in tempor turpis', 'Crimson', 'Além do Rio');
insert into projects (id, title, color, city) values (216, 'lorem id', 'Puce', 'Tyringe');
insert into projects (id, title, color, city) values (217, 'justo sollicitudin ut', 'Purple', 'Cilated');
insert into projects (id, title, color, city) values (218, 'sapien ut', 'Blue', 'Sidi Yahya Ou Saad');
insert into projects (id, title, color, city) values (219, 'dignissim', 'Puce', 'Keli');
insert into projects (id, title, color, city) values (220, 'eget rutrum', 'Green', 'Léfka');
insert into projects (id, title, color, city) values (221, 'laoreet', 'Khaki', 'Ōnojō');
insert into projects (id, title, color, city) values (222, 'suspendisse potenti', 'Crimson', 'Kisai');
insert into projects (id, title, color, city) values (223, 'duis bibendum felis', 'Red', 'Luzon');
insert into projects (id, title, color, city) values (224, 'non mi', 'Aquamarine', 'Stebnyk');
insert into projects (id, title, color, city) values (225, 'gravida nisi at', null, 'Nova Varoš');
insert into projects (id, title, color, city) values (226, 'arcu', 'Indigo', 'Đạ Tẻh');
insert into projects (id, title, color, city) values (227, 'etiam vel', 'Violet', 'Xiangcheng');
insert into projects (id, title, color, city) values (228, 'nisl nunc', 'Teal', 'Belfast');
insert into projects (id, title, color, city) values (229, 'turpis donec posuere', 'Green', 'Maria Cristina');
insert into projects (id, title, color, city) values (230, 'mauris lacinia', null, 'Minas');
insert into projects (id, title, color, city) values (231, 'praesent blandit', 'Aquamarine', 'Malinta');
insert into projects (id, title, color, city) values (232, 'volutpat dui maecenas', 'Crimson', 'Baltimore');
insert into projects (id, title, color, city) values (233, 'aenean auctor gravida', 'Turquoise', 'Agía Varvára');
insert into projects (id, title, color, city) values (234, 'ultricies eu', 'Yellow', 'Bugo');
insert into projects (id, title, color, city) values (235, 'id nulla', 'Pink', 'Los Angeles');
insert into projects (id, title, color, city) values (236, 'amet consectetuer', 'Green', 'Hrazdan');
insert into projects (id, title, color, city) values (237, 'ridiculus', null, 'Ziketan');
insert into projects (id, title, color, city) values (238, 'nam nulla', 'Indigo', 'Wuyahe');
insert into projects (id, title, color, city) values (239, 'malesuada in', 'Pink', 'Shinjō');
insert into projects (id, title, color, city) values (240, 'justo in', 'Mauv', 'Marseille');
insert into projects (id, title, color, city) values (241, 'porttitor lorem', 'Green', 'Tiannan');
insert into projects (id, title, color, city) values (242, 'imperdiet et commodo', 'Violet', 'Mae Sot');
insert into projects (id, title, color, city) values (243, 'id massa id', 'Teal', 'Buturlinovka');
insert into projects (id, title, color, city) values (244, 'dui nec', 'Maroon', 'Jiangnan');
insert into projects (id, title, color, city) values (245, 'nisi nam ultrices', 'Orange', 'Mlangali');
insert into projects (id, title, color, city) values (246, 'lectus suspendisse', 'Puce', 'Apostolove');
insert into projects (id, title, color, city) values (247, 'duis consequat dui', 'Blue', 'Hödrögö');
insert into projects (id, title, color, city) values (248, 'sagittis dui vel', 'Indigo', 'Xingren');
insert into projects (id, title, color, city) values (249, 'est lacinia', 'Orange', 'Stanišić');
insert into projects (id, title, color, city) values (250, 'pede', 'Violet', 'Niechanowo');
insert into projects (id, title, color, city) values (251, 'pede morbi', 'Crimson', 'Bendan');
insert into projects (id, title, color, city) values (252, 'non velit', 'Green', 'Chojnów');
insert into projects (id, title, color, city) values (253, 'in lacus curabitur', null, 'Bicurga');
insert into projects (id, title, color, city) values (254, 'vestibulum', null, 'Xiangride');
insert into projects (id, title, color, city) values (255, 'amet sem fusce', 'Aquamarine', 'Dandian');
insert into projects (id, title, color, city) values (256, 'dapibus dolor', 'Blue', 'Kalungu');
insert into projects (id, title, color, city) values (257, 'vulputate', 'Maroon', 'Chitré');
insert into projects (id, title, color, city) values (258, 'odio', 'Maroon', 'Lapa do Lobo');
insert into projects (id, title, color, city) values (259, 'potenti nullam porttitor', 'Yellow', 'Tuguan');
insert into projects (id, title, color, city) values (260, 'laoreet', 'Mauv', 'Goúrnes');
insert into projects (id, title, color, city) values (261, 'vulputate justo', 'Blue', 'Koreiz');
insert into projects (id, title, color, city) values (262, 'hac habitasse platea', null, 'La Palma');
insert into projects (id, title, color, city) values (263, 'platea', 'Khaki', 'Shanghu');
insert into projects (id, title, color, city) values (264, 'at nulla', 'Indigo', 'Gaoleshan');
insert into projects (id, title, color, city) values (265, 'amet', 'Orange', 'Padre Paraíso');
insert into projects (id, title, color, city) values (266, 'donec', 'Red', 'Coronel Vivida');
insert into projects (id, title, color, city) values (267, 'donec ut mauris', 'Turquoise', 'Kvissleby');
insert into projects (id, title, color, city) values (268, 'tempus sit amet', 'Orange', 'Sōja');
insert into projects (id, title, color, city) values (269, 'quis tortor id', 'Indigo', 'Singapore');
insert into projects (id, title, color, city) values (270, 'posuere cubilia', 'Maroon', 'Dongxi');
insert into projects (id, title, color, city) values (271, 'cubilia curae', 'Orange', 'La Quebrada');
insert into projects (id, title, color, city) values (272, 'diam erat', 'Crimson', 'Hong’an');
insert into projects (id, title, color, city) values (273, 'blandit ultrices', 'Goldenrod', 'Shidu');
insert into projects (id, title, color, city) values (274, 'est phasellus sit', 'Red', 'Amsterdam Noord west');
insert into projects (id, title, color, city) values (275, 'id mauris vulputate', null, 'Carreira');
insert into projects (id, title, color, city) values (276, 'at turpis', 'Green', 'Saint Paul');
insert into projects (id, title, color, city) values (277, 'sollicitudin ut', 'Crimson', 'Watunggong');
insert into projects (id, title, color, city) values (278, 'consequat', 'Green', 'Mobile');
insert into projects (id, title, color, city) values (279, 'purus phasellus', null, 'Ārān Bīdgol');
insert into projects (id, title, color, city) values (280, 'quam', 'Teal', 'Pushkin');
insert into projects (id, title, color, city) values (281, 'sodales', 'Teal', 'Huaitu');
insert into projects (id, title, color, city) values (282, 'ut', 'Teal', 'Sarata');
insert into projects (id, title, color, city) values (283, 'mattis', 'Indigo', 'Hrušovany u Brna');
insert into projects (id, title, color, city) values (284, 'pede justo lacinia', 'Goldenrod', 'Rancanyenang');
insert into projects (id, title, color, city) values (285, 'vestibulum rutrum', 'Turquoise', 'Barda');
insert into projects (id, title, color, city) values (286, 'magnis dis parturient', 'Blue', 'Nakkila');
insert into projects (id, title, color, city) values (287, 'parturient montes', 'Teal', 'Yakovlevo');
insert into projects (id, title, color, city) values (288, 'aenean fermentum', 'Purple', 'Kalchevaya');
insert into projects (id, title, color, city) values (289, 'pellentesque at', 'Crimson', 'Marseille');
insert into projects (id, title, color, city) values (290, 'non mauris', 'Crimson', 'Cagliari');
insert into projects (id, title, color, city) values (291, 'auctor gravida', 'Maroon', 'Qiewa');
insert into projects (id, title, color, city) values (292, 'malesuada in imperdiet', 'Violet', 'Chartres');
insert into projects (id, title, color, city) values (293, 'justo in', 'Turquoise', 'Hongshanyao');
insert into projects (id, title, color, city) values (294, 'dolor vel', 'Khaki', 'Muli');
insert into projects (id, title, color, city) values (295, 'curae nulla', 'Khaki', 'Guluoshan');
insert into projects (id, title, color, city) values (296, 'sem', 'Puce', 'Dongzhou');
insert into projects (id, title, color, city) values (297, 'curabitur gravida', 'Puce', 'Yaté-Barrage');
insert into projects (id, title, color, city) values (298, 'eget rutrum', null, 'Campoalegre');
insert into projects (id, title, color, city) values (299, 'aliquam quis', 'Khaki', 'Miejsce Piastowe');
insert into projects (id, title, color, city) values (300, 'sem duis', 'Purple', 'Medeiros Neto');
insert into projects (id, title, color, city) values (301, 'magnis dis parturient', 'Orange', 'Sucre');
insert into projects (id, title, color, city) values (302, 'ipsum', 'Violet', 'Ludwin');
insert into projects (id, title, color, city) values (303, 'morbi', 'Pink', 'Lomme');
insert into projects (id, title, color, city) values (304, 'ultrices vel', 'Orange', 'Erie');
insert into projects (id, title, color, city) values (305, 'volutpat', 'Khaki', 'Le Havre');
insert into projects (id, title, color, city) values (306, 'ipsum', 'Pink', 'Hudson Bay');
insert into projects (id, title, color, city) values (307, 'suspendisse potenti', 'Mauv', 'Mezhevoy');
insert into projects (id, title, color, city) values (308, 'ultrices libero', 'Turquoise', 'Bascaron');
insert into projects (id, title, color, city) values (309, 'ac tellus', 'Red', 'Karangnunggal');
insert into projects (id, title, color, city) values (310, 'tristique fusce', 'Violet', 'Chengguan');
insert into projects (id, title, color, city) values (311, 'tristique', 'Purple', 'Lyskovo');
insert into projects (id, title, color, city) values (312, 'magna vulputate luctus', 'Goldenrod', 'Houston');
insert into projects (id, title, color, city) values (313, 'parturient', 'Red', 'Killarney');
insert into projects (id, title, color, city) values (314, 'turpis', 'Orange', 'Bordeaux');
insert into projects (id, title, color, city) values (315, 'elementum ligula vehicula', 'Pink', 'Manolás');
insert into projects (id, title, color, city) values (316, 'sed tristique', 'Mauv', 'Ciseureuheun');
insert into projects (id, title, color, city) values (317, 'sit amet cursus', 'Maroon', 'Konārak');
insert into projects (id, title, color, city) values (318, 'sit', null, 'Wajak');
insert into projects (id, title, color, city) values (319, 'integer', 'Pink', 'San Pedro One');
insert into projects (id, title, color, city) values (320, 'mattis', 'Puce', 'Daliu');
insert into projects (id, title, color, city) values (321, 'cras in', 'Mauv', 'Xiaochi');
insert into projects (id, title, color, city) values (322, 'tortor sollicitudin mi', 'Indigo', 'La Punta');
insert into projects (id, title, color, city) values (323, 'aliquam sit', 'Fuscia', 'Lianyuan');
insert into projects (id, title, color, city) values (324, 'vel nulla', 'Violet', 'Cishangang');
insert into projects (id, title, color, city) values (325, 'accumsan', null, 'Dongshe');
insert into projects (id, title, color, city) values (326, 'id lobortis convallis', 'Red', 'Calango');
insert into projects (id, title, color, city) values (327, 'lacinia', 'Indigo', 'Malaga');
insert into projects (id, title, color, city) values (328, 'mi nulla ac', 'Puce', 'Palilula');
insert into projects (id, title, color, city) values (329, 'enim in tempor', null, 'Ledeunu');
insert into projects (id, title, color, city) values (330, 'massa id', 'Pink', 'Thames');
insert into projects (id, title, color, city) values (331, 'risus auctor sed', 'Teal', 'Kajansi');
insert into projects (id, title, color, city) values (332, 'ornare consequat', 'Violet', 'Golubac');
insert into projects (id, title, color, city) values (333, 'sit', null, 'Chaguaní');
insert into projects (id, title, color, city) values (334, 'nulla', 'Blue', 'Fatufaun');
insert into projects (id, title, color, city) values (335, 'quisque arcu libero', 'Purple', 'Regimin');
insert into projects (id, title, color, city) values (336, 'etiam justo', 'Maroon', 'Guolemude');
insert into projects (id, title, color, city) values (337, 'nisl nunc rhoncus', 'Pink', 'Baohe');
insert into projects (id, title, color, city) values (338, 'sed', 'Indigo', 'Ust’-Dzheguta');
insert into projects (id, title, color, city) values (339, 'nonummy integer', 'Blue', 'Vylkove');
insert into projects (id, title, color, city) values (340, 'vitae nisi nam', 'Indigo', 'Keelung');
insert into projects (id, title, color, city) values (341, 'tincidunt nulla', 'Yellow', 'Kolyshley');
insert into projects (id, title, color, city) values (342, 'amet nulla', 'Purple', 'Sancha');
insert into projects (id, title, color, city) values (343, 'morbi non lectus', 'Violet', 'Margarita');
insert into projects (id, title, color, city) values (344, 'parturient montes', 'Khaki', 'Tānsen');
insert into projects (id, title, color, city) values (345, 'pretium quis', 'Crimson', 'Calangain');
insert into projects (id, title, color, city) values (346, 'pede ullamcorper', null, 'Santa Cruz');
insert into projects (id, title, color, city) values (347, 'curae duis faucibus', 'Yellow', 'Zubří');
insert into projects (id, title, color, city) values (348, 'in sapien', 'Pink', 'Yanagawamachi-saiwaichō');
insert into projects (id, title, color, city) values (349, 'felis eu', 'Turquoise', 'Blagoevgrad');
insert into projects (id, title, color, city) values (350, 'curae', 'Violet', 'Yanmenkou');
insert into projects (id, title, color, city) values (351, 'nulla sed', 'Fuscia', 'Gading');
insert into projects (id, title, color, city) values (352, 'in magna bibendum', null, 'Kandete');
insert into projects (id, title, color, city) values (353, 'eros', 'Blue', 'Tikhoretsk');
insert into projects (id, title, color, city) values (354, 'condimentum neque sapien', 'Mauv', 'Kakegawa');
insert into projects (id, title, color, city) values (355, 'vel est', 'Khaki', 'Ouanaminthe');
insert into projects (id, title, color, city) values (356, 'ac', 'Violet', 'La Habana Vieja');
insert into projects (id, title, color, city) values (357, 'donec odio', 'Purple', 'Woodstock');
insert into projects (id, title, color, city) values (358, 'non lectus aliquam', 'Mauv', 'Shibīn al Kawm');
insert into projects (id, title, color, city) values (359, 'ultricies eu', 'Puce', 'Laban');
insert into projects (id, title, color, city) values (360, 'elementum ligula', 'Pink', 'Shardara');
insert into projects (id, title, color, city) values (361, 'diam erat fermentum', 'Goldenrod', 'Choco');
insert into projects (id, title, color, city) values (362, 'ut suscipit a', null, 'Cangkuang');
insert into projects (id, title, color, city) values (363, 'at lorem integer', 'Mauv', 'La Romana');
insert into projects (id, title, color, city) values (364, 'mauris enim leo', 'Blue', 'Penedo');
insert into projects (id, title, color, city) values (365, 'et eros vestibulum', 'Teal', 'Qinlan');
insert into projects (id, title, color, city) values (366, 'posuere felis sed', 'Goldenrod', 'Wawer');
insert into projects (id, title, color, city) values (367, 'nibh in hac', 'Purple', 'Bang Pahan');
insert into projects (id, title, color, city) values (368, 'aliquet maecenas', null, 'Ciechocin');
insert into projects (id, title, color, city) values (369, 'maecenas rhoncus aliquam', 'Goldenrod', 'Ciulu');
insert into projects (id, title, color, city) values (370, 'nunc', 'Goldenrod', 'Simenqian');
insert into projects (id, title, color, city) values (371, 'diam neque', 'Green', 'Podporozh’ye');
insert into projects (id, title, color, city) values (372, 'integer non velit', 'Teal', 'Santa Rita');
insert into projects (id, title, color, city) values (373, 'lectus in quam', 'Crimson', 'Midrand');
insert into projects (id, title, color, city) values (374, 'sit amet nunc', 'Teal', 'Hawassa');
insert into projects (id, title, color, city) values (375, 'nulla facilisi cras', null, 'Oetuke');
insert into projects (id, title, color, city) values (376, 'mus', null, 'Gongfang');
insert into projects (id, title, color, city) values (377, 'semper', 'Pink', 'Beiling');
insert into projects (id, title, color, city) values (378, 'sollicitudin vitae', 'Red', 'Klishkivtsi');
insert into projects (id, title, color, city) values (379, 'rutrum', 'Blue', 'Shuanghe');
insert into projects (id, title, color, city) values (380, 'velit eu est', 'Indigo', 'Zboriv');
insert into projects (id, title, color, city) values (381, 'velit', 'Crimson', 'Maastricht');
insert into projects (id, title, color, city) values (382, 'ante vestibulum ante', 'Turquoise', 'Bernay');
insert into projects (id, title, color, city) values (383, 'morbi non quam', null, 'Biryulëvo Zapadnoye');
insert into projects (id, title, color, city) values (384, 'nullam', 'Pink', 'Gambarjati');
insert into projects (id, title, color, city) values (385, 'erat vestibulum', 'Red', 'Amizmiz');
insert into projects (id, title, color, city) values (386, 'augue vestibulum rutrum', 'Pink', 'Frösön');
insert into projects (id, title, color, city) values (387, 'lobortis est phasellus', 'Yellow', 'Požarevac');
insert into projects (id, title, color, city) values (388, 'cras', 'Pink', 'Otan Aiyegbaju');
insert into projects (id, title, color, city) values (389, 'ipsum ac tellus', 'Violet', 'Wellington');
insert into projects (id, title, color, city) values (390, 'dolor sit', 'Violet', 'Birayang');
insert into projects (id, title, color, city) values (391, 'integer aliquet', 'Violet', 'Ancasti');
insert into projects (id, title, color, city) values (392, 'feugiat et eros', 'Fuscia', 'Dandai');
insert into projects (id, title, color, city) values (393, 'condimentum id luctus', null, 'Aragua de Barcelona');
insert into projects (id, title, color, city) values (394, 'neque', 'Puce', 'Tominian');
insert into projects (id, title, color, city) values (395, 'phasellus sit', 'Green', 'Koblain');
insert into projects (id, title, color, city) values (396, 'posuere cubilia', 'Aquamarine', 'Maceió');
insert into projects (id, title, color, city) values (397, 'tempor convallis', 'Orange', 'Fagersta');
insert into projects (id, title, color, city) values (398, 'praesent lectus vestibulum', 'Pink', 'Ganyesa');
insert into projects (id, title, color, city) values (399, 'volutpat dui maecenas', 'Fuscia', 'Xipu');
insert into projects (id, title, color, city) values (400, 'rhoncus', 'Maroon', 'Pedreira');
insert into projects (id, title, color, city) values (401, 'ultrices aliquet maecenas', 'Crimson', 'Prachatice');
insert into projects (id, title, color, city) values (402, 'mollis molestie', 'Fuscia', 'Sandaoba');
insert into projects (id, title, color, city) values (403, 'pellentesque eget nunc', 'Crimson', 'Yangp''yŏng');
insert into projects (id, title, color, city) values (404, 'lacinia', 'Mauv', 'Changtang');
insert into projects (id, title, color, city) values (405, 'orci mauris lacinia', null, 'Kōnosu');
insert into projects (id, title, color, city) values (406, 'consequat varius', 'Indigo', 'Growong Kidul');
insert into projects (id, title, color, city) values (407, 'posuere cubilia', null, 'Xiangang');
insert into projects (id, title, color, city) values (408, 'ante vivamus tortor', null, 'Pittsburgh');
insert into projects (id, title, color, city) values (409, 'orci luctus et', 'Khaki', 'Cabo Frio');
insert into projects (id, title, color, city) values (410, 'eu massa', 'Goldenrod', 'Główczyce');
insert into projects (id, title, color, city) values (411, 'duis at', 'Red', 'Helsingborg');
insert into projects (id, title, color, city) values (412, 'nulla mollis', null, 'Semamung');
insert into projects (id, title, color, city) values (413, 'magnis dis', 'Turquoise', 'Ayagoz');
insert into projects (id, title, color, city) values (414, 'sem praesent', 'Green', 'Oguta');
insert into projects (id, title, color, city) values (415, 'vel ipsum', 'Aquamarine', 'Xueshan');
insert into projects (id, title, color, city) values (416, 'blandit ultrices enim', 'Blue', 'Waikambila');
insert into projects (id, title, color, city) values (417, 'posuere', 'Mauv', 'La Sierpe');
insert into projects (id, title, color, city) values (418, 'orci', 'Mauv', 'Grammatikó');
insert into projects (id, title, color, city) values (419, 'est donec', 'Aquamarine', 'Sidareja');
insert into projects (id, title, color, city) values (420, 'metus', 'Blue', 'Dimona');
insert into projects (id, title, color, city) values (421, 'elementum', 'Blue', 'Nakanojōmachi');
insert into projects (id, title, color, city) values (422, 'at lorem integer', 'Crimson', 'Huangcaotuo');
insert into projects (id, title, color, city) values (423, 'mauris', null, 'Kajisara');
insert into projects (id, title, color, city) values (424, 'quis orci eget', 'Turquoise', 'Rízoma');
insert into projects (id, title, color, city) values (425, 'eros elementum pellentesque', 'Fuscia', 'Imeni Zhelyabova');
insert into projects (id, title, color, city) values (426, 'habitasse', 'Teal', 'Ambanja');
insert into projects (id, title, color, city) values (427, 'vestibulum', 'Pink', 'Narita');
insert into projects (id, title, color, city) values (428, 'mi in', 'Turquoise', 'Itsukaichi');
insert into projects (id, title, color, city) values (429, 'pharetra magna ac', 'Orange', 'Město');
insert into projects (id, title, color, city) values (430, 'sed justo pellentesque', 'Goldenrod', 'Songkar B');
insert into projects (id, title, color, city) values (431, 'duis', null, 'Stockholm');
insert into projects (id, title, color, city) values (432, 'vitae ipsum aliquam', 'Red', 'Tākestān');
insert into projects (id, title, color, city) values (433, 'massa', 'Teal', 'Dongshui');
insert into projects (id, title, color, city) values (434, 'egestas metus', 'Purple', 'Ibirama');
insert into projects (id, title, color, city) values (435, 'lacinia eget', 'Indigo', 'Odiong');
insert into projects (id, title, color, city) values (436, 'ultrices posuere cubilia', 'Teal', 'Wijewo');
insert into projects (id, title, color, city) values (437, 'non', 'Fuscia', 'Hněvotín');
insert into projects (id, title, color, city) values (438, 'tortor sollicitudin mi', 'Orange', 'Lancaster');
insert into projects (id, title, color, city) values (439, 'orci vehicula', 'Green', 'Frederico Westphalen');
insert into projects (id, title, color, city) values (440, 'pellentesque volutpat dui', null, 'Oleszyce');
insert into projects (id, title, color, city) values (441, 'imperdiet sapien urna', 'Turquoise', 'Yishi');
insert into projects (id, title, color, city) values (442, 'dapibus at diam', 'Pink', 'Jiulonggang');
insert into projects (id, title, color, city) values (443, 'aliquam convallis nunc', 'Green', 'Sumberan');
insert into projects (id, title, color, city) values (444, 'eu', 'Khaki', 'Jinshan');
insert into projects (id, title, color, city) values (445, 'viverra', 'Fuscia', 'Andrushivka');
insert into projects (id, title, color, city) values (446, 'elit proin', 'Puce', 'Yangqiao');
insert into projects (id, title, color, city) values (447, 'amet', 'Khaki', 'Ngromo');
insert into projects (id, title, color, city) values (448, 'lobortis sapien', 'Aquamarine', 'Varkaus');
insert into projects (id, title, color, city) values (449, 'at ipsum', 'Crimson', 'Danderyd');
insert into projects (id, title, color, city) values (450, 'suscipit', null, 'Mertzig');
insert into projects (id, title, color, city) values (451, 'ultrices mattis', 'Pink', 'Dallas');
insert into projects (id, title, color, city) values (452, 'vestibulum aliquet ultrices', 'Green', 'Al Qaţn');
insert into projects (id, title, color, city) values (453, 'vestibulum', 'Crimson', 'Banes');
insert into projects (id, title, color, city) values (454, 'quisque', 'Pink', 'Pacucha');
insert into projects (id, title, color, city) values (455, 'sed augue aliquam', 'Green', 'Buzet');
insert into projects (id, title, color, city) values (456, 'pede', 'Red', 'Yangkou');
insert into projects (id, title, color, city) values (457, 'cubilia', null, 'Ferkessédougou');
insert into projects (id, title, color, city) values (458, 'aenean lectus pellentesque', null, 'Zhaolingpu');
insert into projects (id, title, color, city) values (459, 'tortor id', 'Pink', 'Citeureup');
insert into projects (id, title, color, city) values (460, 'ridiculus mus etiam', 'Blue', 'Kapasan');
insert into projects (id, title, color, city) values (461, 'venenatis', 'Puce', 'Chekmagush');
insert into projects (id, title, color, city) values (462, 'curabitur convallis duis', 'Blue', 'Orizari');
insert into projects (id, title, color, city) values (463, 'nisi', null, 'Katyuzhanka');
insert into projects (id, title, color, city) values (464, 'sit', 'Teal', 'Palue');
insert into projects (id, title, color, city) values (465, 'blandit ultrices enim', 'Purple', 'Puerto Boyacá');
insert into projects (id, title, color, city) values (466, 'scelerisque mauris sit', 'Khaki', 'Karangagung Timur');
insert into projects (id, title, color, city) values (467, 'cubilia curae', 'Crimson', 'Fuvahmulah');
insert into projects (id, title, color, city) values (468, 'vivamus vel', 'Crimson', 'Kampong Cham');
insert into projects (id, title, color, city) values (469, 'nibh in lectus', 'Khaki', 'Ovalle');
insert into projects (id, title, color, city) values (470, 'volutpat dui maecenas', 'Red', 'Buenos Aires');
insert into projects (id, title, color, city) values (471, 'erat curabitur gravida', 'Blue', 'Toulouse');
insert into projects (id, title, color, city) values (472, 'varius integer', 'Puce', 'Gangu Chengguanzhen');
insert into projects (id, title, color, city) values (473, 'dolor vel est', null, 'Heping');
insert into projects (id, title, color, city) values (474, 'habitasse platea', 'Puce', 'Lorient');
insert into projects (id, title, color, city) values (475, 'non mi', 'Violet', 'Castleknock');
insert into projects (id, title, color, city) values (476, 'luctus nec molestie', 'Mauv', 'Meaux');
insert into projects (id, title, color, city) values (477, 'dis parturient montes', null, 'Ojrzeń');
insert into projects (id, title, color, city) values (478, 'lacus at velit', 'Pink', 'København');
insert into projects (id, title, color, city) values (479, 'eu orci mauris', 'Puce', 'Spirit River');
insert into projects (id, title, color, city) values (480, 'mus', 'Goldenrod', 'Châteauroux');
insert into projects (id, title, color, city) values (481, 'adipiscing elit', 'Turquoise', 'Zhanbei');
insert into projects (id, title, color, city) values (482, 'eget congue', 'Red', 'Wushan');
insert into projects (id, title, color, city) values (483, 'consequat dui', 'Turquoise', 'Longfengba');
insert into projects (id, title, color, city) values (484, 'dolor sit amet', 'Maroon', 'Wudil');
insert into projects (id, title, color, city) values (485, 'pellentesque viverra', 'Crimson', 'Cential');
insert into projects (id, title, color, city) values (486, 'suspendisse accumsan', 'Purple', 'Hakha');
insert into projects (id, title, color, city) values (487, 'nulla', null, 'Suai');
insert into projects (id, title, color, city) values (488, 'cum sociis natoque', 'Orange', 'Balai');
insert into projects (id, title, color, city) values (489, 'pellentesque', 'Turquoise', 'Baimaqiao');
insert into projects (id, title, color, city) values (490, 'mollis molestie lorem', 'Pink', 'Talangbetutu');
insert into projects (id, title, color, city) values (491, 'nibh in lectus', 'Indigo', 'Timrat');
insert into projects (id, title, color, city) values (492, 'pretium', 'Mauv', 'Buriwutung');
insert into projects (id, title, color, city) values (493, 'amet erat nulla', 'Maroon', 'Hangkou');
insert into projects (id, title, color, city) values (494, 'velit id', 'Aquamarine', 'Beauvais');
insert into projects (id, title, color, city) values (495, 'tellus in', 'Crimson', 'Satuba');
insert into projects (id, title, color, city) values (496, 'dui maecenas tristique', 'Khaki', 'Qiangqinxue');
insert into projects (id, title, color, city) values (497, 'erat', 'Maroon', 'Toba');
insert into projects (id, title, color, city) values (498, 'consequat morbi a', 'Pink', 'Banjar Dauhpura');
insert into projects (id, title, color, city) values (499, 'vel augue vestibulum', 'Red', 'Serra');
insert into projects (id, title, color, city) values (500, 'porttitor lacus', 'Yellow', 'Sujji');
insert into projects (id, title, color, city) values (501, 'nulla pede ullamcorper', null, 'Manaloal');
insert into projects (id, title, color, city) values (502, 'augue', 'Teal', 'Churovichi');
insert into projects (id, title, color, city) values (503, 'tincidunt eget tempus', null, 'Gongchang Zhen');
insert into projects (id, title, color, city) values (504, 'sapien', 'Maroon', 'Pyatovskiy');
insert into projects (id, title, color, city) values (505, 'praesent', null, 'Barcelona');
insert into projects (id, title, color, city) values (506, 'mus', 'Puce', 'Campo Verde');
insert into projects (id, title, color, city) values (507, 'praesent lectus', null, 'Norfolk');
insert into projects (id, title, color, city) values (508, 'sit amet eleifend', 'Pink', 'Namayingo');
insert into projects (id, title, color, city) values (509, 'lacus at velit', 'Purple', 'Custódia');
insert into projects (id, title, color, city) values (510, 'nisl', 'Indigo', 'Getung');
insert into projects (id, title, color, city) values (511, 'dapibus duis', null, 'Hengshi');
insert into projects (id, title, color, city) values (512, 'est phasellus sit', null, 'Kubang');
insert into projects (id, title, color, city) values (513, 'blandit', null, 'Estância Velha');
insert into projects (id, title, color, city) values (514, 'in tempor', 'Mauv', 'Xazgat');
insert into projects (id, title, color, city) values (515, 'vestibulum', 'Goldenrod', 'Esperanza');
insert into projects (id, title, color, city) values (516, 'quam a', 'Aquamarine', 'South Bend');
insert into projects (id, title, color, city) values (517, 'et ultrices posuere', 'Orange', 'Providencia');
insert into projects (id, title, color, city) values (518, 'commodo', 'Maroon', 'Shiyan');
insert into projects (id, title, color, city) values (519, 'eleifend pede libero', null, 'Dąbrowa');
insert into projects (id, title, color, city) values (520, 'tempus sit', 'Fuscia', 'Kota Kinabalu');
insert into projects (id, title, color, city) values (521, 'faucibus orci', null, 'Schœlcher');
insert into projects (id, title, color, city) values (522, 'semper est', 'Teal', 'Dulangan');
insert into projects (id, title, color, city) values (523, 'sed', 'Yellow', 'Portela');
insert into projects (id, title, color, city) values (524, 'sit', 'Purple', 'Ibiporã');
insert into projects (id, title, color, city) values (525, 'erat quisque erat', 'Fuscia', 'Talok');
insert into projects (id, title, color, city) values (526, 'libero nam', 'Orange', 'Oliveira');
insert into projects (id, title, color, city) values (527, 'id ligula suspendisse', 'Teal', 'Anyuan');
insert into projects (id, title, color, city) values (528, 'suspendisse ornare', 'Orange', 'Mudian');
insert into projects (id, title, color, city) values (529, 'eu est congue', 'Mauv', 'Safed');
insert into projects (id, title, color, city) values (530, 'erat curabitur gravida', 'Orange', 'Temperak');
insert into projects (id, title, color, city) values (531, 'morbi', 'Violet', 'Pandansari');
insert into projects (id, title, color, city) values (532, 'orci mauris lacinia', null, 'Hujiaba');
insert into projects (id, title, color, city) values (533, 'amet erat nulla', 'Teal', 'Belung Satu');
insert into projects (id, title, color, city) values (534, 'lacus at velit', 'Crimson', 'Åkersberga');
insert into projects (id, title, color, city) values (535, 'metus', 'Goldenrod', 'Rędziny');
insert into projects (id, title, color, city) values (536, 'donec semper', 'Blue', 'Pulong Gubat');
insert into projects (id, title, color, city) values (537, 'est', 'Green', 'Ambositra');
insert into projects (id, title, color, city) values (538, 'justo aliquam', 'Purple', 'Carmo do Paranaíba');
insert into projects (id, title, color, city) values (539, 'quis', null, 'Toledo');
insert into projects (id, title, color, city) values (540, 'justo pellentesque viverra', 'Indigo', 'Cotabambas');
insert into projects (id, title, color, city) values (541, 'duis ac', 'Green', 'Balzers');
insert into projects (id, title, color, city) values (542, 'nunc', null, 'Haczów');
insert into projects (id, title, color, city) values (543, 'vestibulum ante ipsum', 'Orange', 'Avdzaga');
insert into projects (id, title, color, city) values (544, 'ultrices posuere', null, 'Gowurdak');
insert into projects (id, title, color, city) values (545, 'quis', 'Purple', 'Bankim');
insert into projects (id, title, color, city) values (546, 'quis', 'Goldenrod', 'La Salud');
insert into projects (id, title, color, city) values (547, 'sed interdum', 'Mauv', 'Los Charrúas');
insert into projects (id, title, color, city) values (548, 'morbi non quam', 'Aquamarine', 'San Nicolas');
insert into projects (id, title, color, city) values (549, 'fusce congue', 'Red', 'Kuala Terengganu');
insert into projects (id, title, color, city) values (550, 'risus praesent', 'Goldenrod', 'Dayou');
insert into projects (id, title, color, city) values (551, 'tempor turpis', 'Pink', 'La Ceja');
insert into projects (id, title, color, city) values (552, 'dolor morbi vel', 'Mauv', 'Nam Khun');
insert into projects (id, title, color, city) values (553, 'cum', null, 'Sagara');
insert into projects (id, title, color, city) values (554, 'sed', 'Aquamarine', 'Zea');
insert into projects (id, title, color, city) values (555, 'habitasse', 'Puce', 'Xindong');
insert into projects (id, title, color, city) values (556, 'elit proin interdum', 'Aquamarine', 'Villa del Rosario');
insert into projects (id, title, color, city) values (557, 'ante vel ipsum', 'Crimson', 'Potštát');
insert into projects (id, title, color, city) values (558, 'rutrum neque aenean', null, 'Portoviejo');
insert into projects (id, title, color, city) values (559, 'augue vestibulum', 'Teal', 'Peterborough');
insert into projects (id, title, color, city) values (560, 'ut ultrices', 'Aquamarine', 'Beigou');
insert into projects (id, title, color, city) values (561, 'tellus semper interdum', 'Yellow', 'Beigang');
insert into projects (id, title, color, city) values (562, 'orci', 'Orange', 'Emiliano Zapata');
insert into projects (id, title, color, city) values (563, 'neque duis', 'Blue', 'San Sebastian');
insert into projects (id, title, color, city) values (564, 'morbi sem mauris', 'Fuscia', 'Novyy Urgal');
insert into projects (id, title, color, city) values (565, 'integer non', 'Fuscia', 'Negombo');
insert into projects (id, title, color, city) values (566, 'venenatis lacinia aenean', 'Fuscia', 'Peremyshl’');
insert into projects (id, title, color, city) values (567, 'consectetuer eget rutrum', 'Blue', 'Thị Trấn Thuận Châu');
insert into projects (id, title, color, city) values (568, 'lectus pellentesque at', 'Blue', 'Whittlesea');
insert into projects (id, title, color, city) values (569, 'morbi porttitor lorem', null, 'Teresa');
insert into projects (id, title, color, city) values (570, 'eget nunc donec', 'Violet', 'Bintang');
insert into projects (id, title, color, city) values (571, 'eu tincidunt', 'Pink', 'Kombapari');
insert into projects (id, title, color, city) values (572, 'vestibulum ante', 'Teal', 'Koslan');
insert into projects (id, title, color, city) values (573, 'mollis', 'Crimson', 'Shkotovo');
insert into projects (id, title, color, city) values (574, 'gravida', null, 'Ylöjärvi');
insert into projects (id, title, color, city) values (575, 'a nibh', 'Green', 'Roma');
insert into projects (id, title, color, city) values (576, 'lobortis est phasellus', 'Mauv', 'Altanbulag');
insert into projects (id, title, color, city) values (577, 'eros elementum', 'Maroon', 'São Joaquim da Barra');
insert into projects (id, title, color, city) values (578, 'maecenas rhoncus aliquam', 'Green', 'Gedaliang');
insert into projects (id, title, color, city) values (579, 'curabitur', 'Maroon', 'Namora');
insert into projects (id, title, color, city) values (580, 'primis in faucibus', 'Goldenrod', 'Karangnongko');
insert into projects (id, title, color, city) values (581, 'in congue etiam', 'Yellow', 'Araruama');
insert into projects (id, title, color, city) values (582, 'mattis odio donec', 'Green', 'Bang Rakam');
insert into projects (id, title, color, city) values (583, 'ut blandit', 'Aquamarine', 'Zhangjiafan');
insert into projects (id, title, color, city) values (584, 'ipsum primis in', 'Mauv', 'Nanterre');
insert into projects (id, title, color, city) values (585, 'dui nec', 'Aquamarine', 'Calingcing');
insert into projects (id, title, color, city) values (586, 'elit', 'Maroon', 'Songea');
insert into projects (id, title, color, city) values (587, 'mattis', 'Yellow', 'Tamel');
insert into projects (id, title, color, city) values (588, 'sed', 'Fuscia', 'Fort Worth');
insert into projects (id, title, color, city) values (589, 'eros vestibulum', 'Fuscia', 'Benger');
insert into projects (id, title, color, city) values (590, 'nulla', 'Puce', 'Carman');
insert into projects (id, title, color, city) values (591, 'montes', 'Yellow', 'Vagonoremont');
insert into projects (id, title, color, city) values (592, 'hac', 'Orange', 'Watuagung');
insert into projects (id, title, color, city) values (593, 'nec', 'Blue', 'Canggetelo');
insert into projects (id, title, color, city) values (594, 'leo pellentesque', 'Fuscia', 'Zarzal');
insert into projects (id, title, color, city) values (595, 'in', 'Violet', 'Solnice');
insert into projects (id, title, color, city) values (596, 'magna ac', 'Teal', 'Lourdes');
insert into projects (id, title, color, city) values (597, 'vitae consectetuer eget', 'Indigo', 'Witkowo');
insert into projects (id, title, color, city) values (598, 'venenatis', 'Indigo', 'Shenji');
insert into projects (id, title, color, city) values (599, 'turpis elementum ligula', 'Aquamarine', 'Belogorsk');
insert into projects (id, title, color, city) values (600, 'nam ultrices', 'Aquamarine', 'Zhanxu');
insert into projects (id, title, color, city) values (601, 'eget orci vehicula', 'Maroon', 'Géfyra');
insert into projects (id, title, color, city) values (602, 'sociis', 'Aquamarine', 'Bao’an');
insert into projects (id, title, color, city) values (603, 'erat curabitur', 'Turquoise', 'Solânea');
insert into projects (id, title, color, city) values (604, 'volutpat in congue', 'Khaki', 'Ganhe');
insert into projects (id, title, color, city) values (605, 'in purus eu', null, 'Kassiri');
insert into projects (id, title, color, city) values (606, 'vel accumsan', 'Blue', 'Varser');
insert into projects (id, title, color, city) values (607, 'lobortis', 'Khaki', 'Sarreguemines');
insert into projects (id, title, color, city) values (608, 'lobortis ligula', 'Orange', 'Tabalong');
insert into projects (id, title, color, city) values (609, 'felis donec', 'Violet', 'Malita');
insert into projects (id, title, color, city) values (610, 'non', 'Orange', 'Sukatani');
insert into projects (id, title, color, city) values (611, 'pellentesque ultrices phasellus', 'Indigo', 'Phù Cát');
insert into projects (id, title, color, city) values (612, 'leo odio', 'Khaki', 'Osięciny');
insert into projects (id, title, color, city) values (613, 'augue aliquam erat', 'Maroon', 'Rokytne');
insert into projects (id, title, color, city) values (614, 'massa', null, 'Alquízar');
insert into projects (id, title, color, city) values (615, 'gravida nisi at', 'Mauv', 'Petaluma');
insert into projects (id, title, color, city) values (616, 'dolor sit', 'Khaki', 'Karangmulya');
insert into projects (id, title, color, city) values (617, 'platea dictumst', 'Teal', 'Shuangshan');
insert into projects (id, title, color, city) values (618, 'sit amet consectetuer', 'Mauv', 'Caen');
insert into projects (id, title, color, city) values (619, 'varius', 'Khaki', 'Colcabamba');
insert into projects (id, title, color, city) values (620, 'rutrum at lorem', 'Yellow', 'Włocławek');
insert into projects (id, title, color, city) values (621, 'tempus vel pede', 'Green', 'Hamburg Bramfeld');
insert into projects (id, title, color, city) values (622, 'ultrices', 'Purple', 'Pingtang');
insert into projects (id, title, color, city) values (623, 'aliquet at', 'Yellow', 'Kunheda Woerzu Manzu');
insert into projects (id, title, color, city) values (624, 'tortor', 'Purple', 'Zhovti Vody');
insert into projects (id, title, color, city) values (625, 'orci luctus et', 'Red', 'Hanjianglu');
insert into projects (id, title, color, city) values (626, 'erat nulla', 'Fuscia', 'Geoktschai');
insert into projects (id, title, color, city) values (627, 'donec diam neque', 'Aquamarine', 'Konstantinovo');
insert into projects (id, title, color, city) values (628, 'cras', 'Turquoise', 'Bonneuil-sur-Marne');
insert into projects (id, title, color, city) values (629, 'purus eu', 'Orange', 'Saba Yoi');
insert into projects (id, title, color, city) values (630, 'quis lectus', null, 'Tammela');
insert into projects (id, title, color, city) values (631, 'non lectus aliquam', 'Orange', 'Madura');
insert into projects (id, title, color, city) values (632, 'vulputate elementum nullam', 'Goldenrod', 'Thị Trấn Văn Quan');
insert into projects (id, title, color, city) values (633, 'nunc', 'Teal', 'Jatisari');
insert into projects (id, title, color, city) values (634, 'proin', 'Turquoise', 'St. Catharines');
insert into projects (id, title, color, city) values (635, 'aliquet pulvinar sed', 'Fuscia', 'Krasna');
insert into projects (id, title, color, city) values (636, 'sem duis', 'Violet', 'Nam Kliang');
insert into projects (id, title, color, city) values (637, 'faucibus orci', 'Indigo', 'Wangcun');
insert into projects (id, title, color, city) values (638, 'sociis natoque', 'Blue', 'Lansing');
insert into projects (id, title, color, city) values (639, 'imperdiet', 'Teal', 'Al Ḩashwah');
insert into projects (id, title, color, city) values (640, 'turpis enim blandit', 'Crimson', 'Carleton Place');
insert into projects (id, title, color, city) values (641, 'fringilla rhoncus mauris', 'Purple', 'Vallauris');
insert into projects (id, title, color, city) values (642, 'accumsan', 'Pink', 'Al Madīd');
insert into projects (id, title, color, city) values (643, 'vivamus vel', 'Pink', 'Pskov');
insert into projects (id, title, color, city) values (644, 'gravida sem praesent', 'Red', 'Chishtiān Mandi');
insert into projects (id, title, color, city) values (645, 'in', 'Aquamarine', 'Levoberezhnaya');
insert into projects (id, title, color, city) values (646, 'interdum', 'Khaki', 'Tall Tamr');
insert into projects (id, title, color, city) values (647, 'commodo', 'Puce', 'Zala');
insert into projects (id, title, color, city) values (648, 'amet consectetuer adipiscing', 'Goldenrod', 'Sokol');
insert into projects (id, title, color, city) values (649, 'accumsan odio curabitur', 'Khaki', 'San Jose');
insert into projects (id, title, color, city) values (650, 'venenatis', 'Maroon', 'Sydney Mines');
insert into projects (id, title, color, city) values (651, 'porttitor pede', 'Blue', 'Dong Charoen');
insert into projects (id, title, color, city) values (652, 'quam', 'Khaki', 'Kafr az Zayyāt');
insert into projects (id, title, color, city) values (653, 'accumsan odio', 'Goldenrod', 'Khánh Hải');
insert into projects (id, title, color, city) values (654, 'vel', 'Aquamarine', 'Kostyantynivka');
insert into projects (id, title, color, city) values (655, 'pede lobortis ligula', 'Indigo', 'San Diego');
insert into projects (id, title, color, city) values (656, 'urna', 'Pink', 'Songjiang');
insert into projects (id, title, color, city) values (657, 'orci luctus', 'Indigo', 'Zaraza');
insert into projects (id, title, color, city) values (658, 'turpis adipiscing', 'Goldenrod', 'Chumpi');
insert into projects (id, title, color, city) values (659, 'primis', 'Crimson', 'Göteborg');
insert into projects (id, title, color, city) values (660, 'nibh in', 'Fuscia', 'Kiltamagh');
insert into projects (id, title, color, city) values (661, 'eu felis fusce', 'Khaki', 'Juripiranga');
insert into projects (id, title, color, city) values (662, 'lectus', 'Red', 'Flores da Cunha');
insert into projects (id, title, color, city) values (663, 'scelerisque quam', 'Green', 'Kebonan');
insert into projects (id, title, color, city) values (664, 'vestibulum quam', 'Turquoise', 'Žabčice');
insert into projects (id, title, color, city) values (665, 'eget', 'Indigo', 'Huntsville');
insert into projects (id, title, color, city) values (666, 'vivamus', 'Yellow', 'Timrå');
insert into projects (id, title, color, city) values (667, 'penatibus et magnis', 'Crimson', 'Valence');
insert into projects (id, title, color, city) values (668, 'congue risus', 'Fuscia', 'Liugong');
insert into projects (id, title, color, city) values (669, 'mauris vulputate elementum', 'Teal', 'Horní Bečva');
insert into projects (id, title, color, city) values (670, 'dolor morbi', 'Khaki', 'Baranowo');
insert into projects (id, title, color, city) values (671, 'amet lobortis sapien', 'Teal', 'Krasnofarfornyy');
insert into projects (id, title, color, city) values (672, 'vulputate elementum', 'Maroon', 'Hetoudian');
insert into projects (id, title, color, city) values (673, 'rhoncus', 'Indigo', 'Wiązownica');
insert into projects (id, title, color, city) values (674, 'at turpis donec', 'Aquamarine', 'Aquiraz');
insert into projects (id, title, color, city) values (675, 'eu massa', null, 'Dongsheng');
insert into projects (id, title, color, city) values (676, 'pellentesque ultrices', 'Crimson', 'Borås');
insert into projects (id, title, color, city) values (677, 'erat', null, 'Montasik');
insert into projects (id, title, color, city) values (678, 'in', 'Blue', 'Macheke');
insert into projects (id, title, color, city) values (679, 'sed nisl nunc', 'Red', 'Schaan');
insert into projects (id, title, color, city) values (680, 'faucibus', null, 'Eséka');
insert into projects (id, title, color, city) values (681, 'in faucibus', null, 'Buenavista');
insert into projects (id, title, color, city) values (682, 'elit proin', 'Goldenrod', 'Nizhniy Kurkuzhin');
insert into projects (id, title, color, city) values (683, 'pede malesuada', 'Red', 'Tagum');
insert into projects (id, title, color, city) values (684, 'massa volutpat convallis', 'Blue', 'Tiaong');
insert into projects (id, title, color, city) values (685, 'tortor', 'Red', 'Jiushe');
insert into projects (id, title, color, city) values (686, 'dictumst maecenas ut', null, 'Nizhniy Kislyay');
insert into projects (id, title, color, city) values (687, 'in leo', 'Aquamarine', 'Wootton');
insert into projects (id, title, color, city) values (688, 'tellus', 'Maroon', 'Quba');
insert into projects (id, title, color, city) values (689, 'mauris viverra diam', 'Fuscia', 'Guabito');
insert into projects (id, title, color, city) values (690, 'rhoncus aliquet', 'Teal', 'Karangora');
insert into projects (id, title, color, city) values (691, 'erat curabitur', 'Red', 'Carrigtwohill');
insert into projects (id, title, color, city) values (692, 'ullamcorper augue a', 'Teal', 'Mari');
insert into projects (id, title, color, city) values (693, 'mattis nibh', 'Pink', 'Babakanbungur');
insert into projects (id, title, color, city) values (694, 'justo', 'Teal', 'Bairro Assunção Piedade');
insert into projects (id, title, color, city) values (695, 'suspendisse', 'Turquoise', 'Vedène');
insert into projects (id, title, color, city) values (696, 'commodo vulputate justo', 'Purple', 'Bull Savanna');
insert into projects (id, title, color, city) values (697, 'pretium iaculis diam', 'Khaki', 'Xinfengjie');
insert into projects (id, title, color, city) values (698, 'nulla suscipit ligula', 'Pink', 'Yenangyaung');
insert into projects (id, title, color, city) values (699, 'nulla', 'Yellow', 'Dzaoudzi');
insert into projects (id, title, color, city) values (700, 'sed', 'Indigo', 'Liantan');
insert into projects (id, title, color, city) values (701, 'duis ac nibh', null, 'Wairiang');
insert into projects (id, title, color, city) values (702, 'porttitor pede', 'Green', 'Daruoyan');
insert into projects (id, title, color, city) values (703, 'sed vel enim', 'Puce', 'Cikembar');
insert into projects (id, title, color, city) values (704, 'eu sapien', 'Mauv', 'Yisuhe');
insert into projects (id, title, color, city) values (705, 'ornare', 'Goldenrod', 'Sui’an');
insert into projects (id, title, color, city) values (706, 'curae mauris', 'Purple', 'Prostřední Bečva');
insert into projects (id, title, color, city) values (707, 'cubilia curae nulla', 'Teal', 'Maguling');
insert into projects (id, title, color, city) values (708, 'tempor', null, 'Tsant');
insert into projects (id, title, color, city) values (709, 'odio condimentum id', 'Turquoise', 'Caxias');
insert into projects (id, title, color, city) values (710, 'enim in', 'Blue', 'Napel');
insert into projects (id, title, color, city) values (711, 'platea dictumst etiam', 'Orange', 'Sơn Trà');
insert into projects (id, title, color, city) values (712, 'facilisi cras non', 'Goldenrod', 'Lunenburg');
insert into projects (id, title, color, city) values (713, 'ultrices posuere cubilia', 'Khaki', 'Gusang');
insert into projects (id, title, color, city) values (714, 'at feugiat', 'Khaki', 'Calumpang');
insert into projects (id, title, color, city) values (715, 'quam', 'Blue', 'Rtyně v Podkrkonoší');
insert into projects (id, title, color, city) values (716, 'luctus et ultrices', 'Red', 'Babana');
insert into projects (id, title, color, city) values (717, 'tellus nulla', 'Khaki', 'Środa Wielkopolska');
insert into projects (id, title, color, city) values (718, 'elementum in', 'Aquamarine', 'Oji River');
insert into projects (id, title, color, city) values (719, 'nulla', 'Crimson', 'Cisaro');
insert into projects (id, title, color, city) values (720, 'vehicula', null, 'Täby');
insert into projects (id, title, color, city) values (721, 'aliquam augue quam', 'Mauv', 'Sorochuco');
insert into projects (id, title, color, city) values (722, 'curae mauris', 'Yellow', 'Xiaxi');
insert into projects (id, title, color, city) values (723, 'libero', 'Puce', 'Xinhe');
insert into projects (id, title, color, city) values (724, 'iaculis', 'Mauv', 'Göteborg');
insert into projects (id, title, color, city) values (725, 'amet nunc', 'Aquamarine', 'Medan');
insert into projects (id, title, color, city) values (726, 'id ornare', 'Puce', 'Taurija');
insert into projects (id, title, color, city) values (727, 'a odio in', 'Violet', 'San Felipe');
insert into projects (id, title, color, city) values (728, 'diam', 'Pink', 'Besao');
insert into projects (id, title, color, city) values (729, 'velit', null, 'Bykhaw');
insert into projects (id, title, color, city) values (730, 'in faucibus orci', 'Aquamarine', 'Pyrzyce');
insert into projects (id, title, color, city) values (731, 'ut', null, 'Olyshivka');
insert into projects (id, title, color, city) values (732, 'hac', 'Pink', 'Karangdalam');
insert into projects (id, title, color, city) values (733, 'amet eros', 'Puce', 'Bairro dos Marinheiros');
insert into projects (id, title, color, city) values (734, 'dapibus', 'Teal', 'Monte Agudo');
insert into projects (id, title, color, city) values (735, 'leo maecenas pulvinar', 'Pink', 'Beiguoyuan');
insert into projects (id, title, color, city) values (736, 'maecenas rhoncus', 'Yellow', 'Muzidian');
insert into projects (id, title, color, city) values (737, 'in libero ut', 'Fuscia', 'Deir Ḥannā');
insert into projects (id, title, color, city) values (738, 'luctus et ultrices', 'Violet', 'Chai Nat');
insert into projects (id, title, color, city) values (739, 'ridiculus mus', 'Purple', 'Zghartā');
insert into projects (id, title, color, city) values (740, 'sem', 'Fuscia', 'Thành Phố Hạ Long');
insert into projects (id, title, color, city) values (741, 'tempor', null, 'Songmuping');
insert into projects (id, title, color, city) values (742, 'enim', 'Fuscia', 'Dadong');
insert into projects (id, title, color, city) values (743, 'proin eu', 'Yellow', 'Polos');
insert into projects (id, title, color, city) values (744, 'id ligula suspendisse', 'Blue', 'Bor Tungge');
insert into projects (id, title, color, city) values (745, 'sapien', 'Turquoise', 'Saboyá');
insert into projects (id, title, color, city) values (746, 'felis sed', 'Purple', 'Barajevo');
insert into projects (id, title, color, city) values (747, 'purus sit amet', null, 'Jingxin');
insert into projects (id, title, color, city) values (748, 'orci eget', 'Indigo', 'Jiangshan');
insert into projects (id, title, color, city) values (749, 'iaculis congue', 'Turquoise', 'Dangbigih');
insert into projects (id, title, color, city) values (750, 'rhoncus dui vel', 'Crimson', 'Youwei');
insert into projects (id, title, color, city) values (751, 'elementum pellentesque quisque', 'Khaki', 'Jorok Dalam');
insert into projects (id, title, color, city) values (752, 'nulla', 'Purple', 'Laoxialu');
insert into projects (id, title, color, city) values (753, 'dapibus duis', 'Blue', 'Angao');
insert into projects (id, title, color, city) values (754, 'amet sapien', 'Goldenrod', 'Cibunar');
insert into projects (id, title, color, city) values (755, 'pretium iaculis diam', 'Turquoise', 'Tabālah');
insert into projects (id, title, color, city) values (756, 'proin leo', 'Blue', 'Ji’an');
insert into projects (id, title, color, city) values (757, 'etiam', 'Khaki', 'Wangcun');
insert into projects (id, title, color, city) values (758, 'nibh', 'Aquamarine', 'Třebíč');
insert into projects (id, title, color, city) values (759, 'pretium', 'Mauv', 'El Paso');
insert into projects (id, title, color, city) values (760, 'ultrices', 'Aquamarine', 'Zaymishche');
insert into projects (id, title, color, city) values (761, 'mi', 'Goldenrod', 'Mölndal');
insert into projects (id, title, color, city) values (762, 'tellus in sagittis', null, 'Cateel');
insert into projects (id, title, color, city) values (763, 'sapien sapien', 'Pink', 'Aībak');
insert into projects (id, title, color, city) values (764, 'quam turpis', 'Indigo', 'Ábrego');
insert into projects (id, title, color, city) values (765, 'pulvinar sed', 'Mauv', 'Gewanē');
insert into projects (id, title, color, city) values (766, 'pede', 'Fuscia', 'Shijak');
insert into projects (id, title, color, city) values (767, 'hac', 'Goldenrod', 'General Martín Miguel de Güemes');
insert into projects (id, title, color, city) values (768, 'montes nascetur', 'Crimson', 'Kurashiki');
insert into projects (id, title, color, city) values (769, 'nulla facilisi cras', 'Pink', 'Rudna Mała');
insert into projects (id, title, color, city) values (770, 'mattis', null, 'Kökar');
insert into projects (id, title, color, city) values (771, 'sapien', null, 'Magoúla');
insert into projects (id, title, color, city) values (772, 'vel accumsan tellus', 'Teal', 'Guangfu');
insert into projects (id, title, color, city) values (773, 'duis consequat', 'Puce', 'Makiyivka');
insert into projects (id, title, color, city) values (774, 'nulla', null, 'Bébédja');
insert into projects (id, title, color, city) values (775, 'nisi nam ultrices', 'Aquamarine', 'Karanganyar');
insert into projects (id, title, color, city) values (776, 'nunc proin', 'Puce', 'Buenavista');
insert into projects (id, title, color, city) values (777, 'tincidunt nulla', 'Purple', 'Thung Song');
insert into projects (id, title, color, city) values (778, 'platea dictumst', 'Orange', 'Shu');
insert into projects (id, title, color, city) values (779, 'in hac', 'Orange', 'Sabnova');
insert into projects (id, title, color, city) values (780, 'ut nunc', 'Pink', 'Al Matūn');
insert into projects (id, title, color, city) values (781, 'eu', 'Crimson', 'Limanancong');
insert into projects (id, title, color, city) values (782, 'lacinia', 'Yellow', 'Fencheng');
insert into projects (id, title, color, city) values (783, 'lectus pellentesque at', 'Violet', 'Béreldange');
insert into projects (id, title, color, city) values (784, 'arcu sed augue', 'Maroon', 'Sobue');
insert into projects (id, title, color, city) values (785, 'gravida sem', 'Orange', 'Kembangkerang Lauk Timur');
insert into projects (id, title, color, city) values (786, 'donec ut', 'Puce', 'Hekou');
insert into projects (id, title, color, city) values (787, 'volutpat', 'Goldenrod', 'Chatuchak');
insert into projects (id, title, color, city) values (788, 'cursus urna ut', 'Red', 'Alis');
insert into projects (id, title, color, city) values (789, 'suspendisse', 'Fuscia', 'Kwikila');
insert into projects (id, title, color, city) values (790, 'eget', 'Red', 'Kazanlŭk');
insert into projects (id, title, color, city) values (791, 'molestie', 'Teal', 'Doropayung');
insert into projects (id, title, color, city) values (792, 'faucibus', 'Violet', 'Haifa');
insert into projects (id, title, color, city) values (793, 'nisi', 'Puce', 'Forquilhinha');
insert into projects (id, title, color, city) values (794, 'eu', 'Blue', 'Chame');
insert into projects (id, title, color, city) values (795, 'maecenas tincidunt', 'Green', 'Yanwan');
insert into projects (id, title, color, city) values (796, 'vel lectus in', 'Indigo', 'Beizhouzi');
insert into projects (id, title, color, city) values (797, 'donec semper sapien', 'Orange', 'Labuan');
insert into projects (id, title, color, city) values (798, 'mattis egestas metus', 'Khaki', 'Tantou');
insert into projects (id, title, color, city) values (799, 'ligula suspendisse ornare', 'Green', 'Itaparica');
insert into projects (id, title, color, city) values (800, 'quam', null, 'Bairro');
insert into projects (id, title, color, city) values (801, 'enim', 'Pink', 'San Vicente');
insert into projects (id, title, color, city) values (802, 'eros', 'Yellow', 'Lingzhi');
insert into projects (id, title, color, city) values (803, 'convallis nunc', null, 'Beo');
insert into projects (id, title, color, city) values (804, 'risus', 'Turquoise', 'Dicun');
insert into projects (id, title, color, city) values (805, 'luctus tincidunt', 'Orange', 'Lesnikovo');
insert into projects (id, title, color, city) values (806, 'phasellus id', 'Teal', 'Chvaletice');
insert into projects (id, title, color, city) values (807, 'leo odio', 'Khaki', 'Jinquan');
insert into projects (id, title, color, city) values (808, 'suspendisse', 'Fuscia', 'Nandayure');
insert into projects (id, title, color, city) values (809, 'morbi vel', 'Maroon', 'Jiuxian');
insert into projects (id, title, color, city) values (810, 'viverra dapibus', 'Fuscia', 'Marseille');
insert into projects (id, title, color, city) values (811, 'ipsum dolor', 'Indigo', 'Hong’an Chengguanzhen');
insert into projects (id, title, color, city) values (812, 'nisl nunc', 'Yellow', 'Liminka');
insert into projects (id, title, color, city) values (813, 'in', 'Teal', 'Bulog');
insert into projects (id, title, color, city) values (814, 'sapien varius', 'Goldenrod', 'Río Grande');
insert into projects (id, title, color, city) values (815, 'cursus', 'Aquamarine', 'Shuanghe');
insert into projects (id, title, color, city) values (816, 'sagittis dui vel', 'Fuscia', 'Xiongshan');
insert into projects (id, title, color, city) values (817, 'arcu adipiscing', 'Maroon', 'Mulyadadi');
insert into projects (id, title, color, city) values (818, 'eleifend pede', 'Fuscia', 'Utajärvi');
insert into projects (id, title, color, city) values (819, 'curae mauris viverra', 'Mauv', 'Gore');
insert into projects (id, title, color, city) values (820, 'vitae', 'Khaki', 'Krajan Kinanti');
insert into projects (id, title, color, city) values (821, 'a', 'Red', 'Tubod');
insert into projects (id, title, color, city) values (822, 'consectetuer adipiscing', null, 'Frederiksberg');
insert into projects (id, title, color, city) values (823, 'aliquam sit', 'Khaki', 'Jindřichův Hradec');
insert into projects (id, title, color, city) values (824, 'donec', 'Pink', 'Chenôve');
insert into projects (id, title, color, city) values (825, 'iaculis justo', 'Orange', 'Gushui');
insert into projects (id, title, color, city) values (826, 'quis lectus', 'Puce', 'Chortkiv');
insert into projects (id, title, color, city) values (827, 'sem sed', 'Orange', 'Borek');
insert into projects (id, title, color, city) values (828, 'vestibulum ante', 'Pink', 'Los Angeles');
insert into projects (id, title, color, city) values (829, 'pede', null, 'Popovi');
insert into projects (id, title, color, city) values (830, 'blandit ultrices', 'Turquoise', 'San Eugenio');
insert into projects (id, title, color, city) values (831, 'amet', 'Turquoise', 'Calaya');
insert into projects (id, title, color, city) values (832, 'habitasse platea', 'Khaki', 'Maloyaroslavets');
insert into projects (id, title, color, city) values (833, 'a', 'Khaki', 'Hongqi');
insert into projects (id, title, color, city) values (834, 'massa tempor convallis', 'Puce', 'Qazax');
insert into projects (id, title, color, city) values (835, 'molestie', null, 'Feilaixia');
insert into projects (id, title, color, city) values (836, 'sollicitudin ut', 'Maroon', 'Oetutulul');
insert into projects (id, title, color, city) values (837, 'id', 'Khaki', 'Tetyushi');
insert into projects (id, title, color, city) values (838, 'nulla', 'Teal', 'Rainis');
insert into projects (id, title, color, city) values (839, 'eleifend luctus', 'Red', 'New York City');
insert into projects (id, title, color, city) values (840, 'dapibus dolor vel', 'Purple', 'Laval');
insert into projects (id, title, color, city) values (841, 'rutrum rutrum neque', null, 'Mounlapamôk');
insert into projects (id, title, color, city) values (842, 'justo maecenas rhoncus', 'Maroon', 'Hushan');
insert into projects (id, title, color, city) values (843, 'ut massa quis', null, 'Orlovskiy');
insert into projects (id, title, color, city) values (844, 'commodo vulputate justo', 'Goldenrod', 'Tukuyu');
insert into projects (id, title, color, city) values (845, 'ante', 'Puce', 'Chester');
insert into projects (id, title, color, city) values (846, 'orci', 'Turquoise', 'Comodoro Rivadavia');
insert into projects (id, title, color, city) values (847, 'nunc', 'Crimson', 'Novyy Urgal');
insert into projects (id, title, color, city) values (848, 'pede', 'Violet', 'Thành Phố Hạ Long');
insert into projects (id, title, color, city) values (849, 'felis', null, 'Issy-les-Moulineaux');
insert into projects (id, title, color, city) values (850, 'massa', 'Aquamarine', 'Sandymount');
insert into projects (id, title, color, city) values (851, 'libero nullam sit', 'Teal', 'Paratinga');
insert into projects (id, title, color, city) values (852, 'turpis elementum', 'Aquamarine', 'Batojaran');
insert into projects (id, title, color, city) values (853, 'elementum', 'Indigo', 'Uvarovka');
insert into projects (id, title, color, city) values (854, 'orci', 'Green', 'Eschweiler');
insert into projects (id, title, color, city) values (855, 'consequat', 'Maroon', 'Livramento');
insert into projects (id, title, color, city) values (856, 'ac leo pellentesque', 'Indigo', 'Colorado Springs');
insert into projects (id, title, color, city) values (857, 'quam pede lobortis', 'Teal', 'Wangmang');
insert into projects (id, title, color, city) values (858, 'ante', 'Green', 'Oslo');
insert into projects (id, title, color, city) values (859, 'eget', 'Turquoise', 'Zabaykal’sk');
insert into projects (id, title, color, city) values (860, 'eu massa', 'Khaki', 'Goryachevodskiy');
insert into projects (id, title, color, city) values (861, 'nisi vulputate nonummy', 'Fuscia', 'Custódia');
insert into projects (id, title, color, city) values (862, 'pede', 'Blue', 'Bor');
insert into projects (id, title, color, city) values (863, 'viverra diam vitae', 'Khaki', 'Jam');
insert into projects (id, title, color, city) values (864, 'massa', 'Red', 'Morelos');
insert into projects (id, title, color, city) values (865, 'dictumst', 'Aquamarine', 'Manta');
insert into projects (id, title, color, city) values (866, 'erat fermentum justo', 'Red', 'Duofudu');
insert into projects (id, title, color, city) values (867, 'non ligula', 'Fuscia', 'Mealhada');
insert into projects (id, title, color, city) values (868, 'consequat dui', 'Puce', 'Igbo-Ukwu');
insert into projects (id, title, color, city) values (869, 'accumsan tellus nisi', 'Indigo', 'Żelazków');
insert into projects (id, title, color, city) values (870, 'elementum ligula vehicula', 'Indigo', 'Egvekinot');
insert into projects (id, title, color, city) values (871, 'sagittis nam', 'Goldenrod', 'Tromsø');
insert into projects (id, title, color, city) values (872, 'lacus at turpis', 'Crimson', 'Manturovo');
insert into projects (id, title, color, city) values (873, 'curae nulla dapibus', 'Green', 'Pimian');
insert into projects (id, title, color, city) values (874, 'odio', 'Green', 'Leninogorsk');
insert into projects (id, title, color, city) values (875, 'eget', 'Teal', 'Al ‘Ulá');
insert into projects (id, title, color, city) values (876, 'nulla', 'Red', 'Dengyue');
insert into projects (id, title, color, city) values (877, 'mollis', 'Green', 'Colegiales');
insert into projects (id, title, color, city) values (878, 'dolor sit', 'Teal', 'Dundrum');
insert into projects (id, title, color, city) values (879, 'lacinia sapien quis', 'Green', 'Baixo Guandu');
insert into projects (id, title, color, city) values (880, 'nullam porttitor lacus', 'Violet', 'Kasreman');
insert into projects (id, title, color, city) values (881, 'sed sagittis', 'Mauv', 'Ruda Śląska');
insert into projects (id, title, color, city) values (882, 'consequat', 'Mauv', 'Enköping');
insert into projects (id, title, color, city) values (883, 'congue etiam justo', null, 'Clogherhead');
insert into projects (id, title, color, city) values (884, 'aliquet', 'Indigo', 'Foumbouni');
insert into projects (id, title, color, city) values (885, 'imperdiet', 'Teal', 'Mesopotamía');
insert into projects (id, title, color, city) values (886, 'diam nam tristique', 'Indigo', 'Dahuangwei');
insert into projects (id, title, color, city) values (887, 'nulla integer', 'Red', 'Brotas');
insert into projects (id, title, color, city) values (888, 'ante ipsum primis', 'Fuscia', 'Meylan');
insert into projects (id, title, color, city) values (889, 'eleifend', 'Crimson', 'Sanhe');
insert into projects (id, title, color, city) values (890, 'vel enim', 'Fuscia', 'Banjar Dharmasemedi');
insert into projects (id, title, color, city) values (891, 'tincidunt', null, 'Moyynkum');
insert into projects (id, title, color, city) values (892, 'nisl', 'Pink', 'Simpanganduwet');
insert into projects (id, title, color, city) values (893, 'pellentesque volutpat dui', 'Indigo', 'Oslo');
insert into projects (id, title, color, city) values (894, 'ornare consequat', 'Turquoise', 'Paris La Défense');
insert into projects (id, title, color, city) values (895, 'ante', 'Aquamarine', 'Aş Şanamayn');
insert into projects (id, title, color, city) values (896, 'a suscipit nulla', 'Purple', 'Guanban');
insert into projects (id, title, color, city) values (897, 'consequat lectus in', 'Blue', 'Chai Nat');
insert into projects (id, title, color, city) values (898, 'sit amet', 'Blue', 'Independencia');
insert into projects (id, title, color, city) values (899, 'proin', 'Yellow', 'Oetutulul');
insert into projects (id, title, color, city) values (900, 'rhoncus aliquet', 'Aquamarine', 'Paola');
insert into projects (id, title, color, city) values (901, 'massa quis augue', 'Teal', 'Presidente Médici');
insert into projects (id, title, color, city) values (902, 'tempus vivamus', null, 'Butare');
insert into projects (id, title, color, city) values (903, 'aenean sit amet', 'Fuscia', 'Bayog');
insert into projects (id, title, color, city) values (904, 'natoque penatibus et', 'Maroon', 'Kroczyce');
insert into projects (id, title, color, city) values (905, 'nisi volutpat', 'Pink', 'Fier-Çifçi');
insert into projects (id, title, color, city) values (906, 'eu orci', 'Fuscia', 'Baishui');
insert into projects (id, title, color, city) values (907, 'suspendisse potenti in', 'Orange', 'Santana do Paraíso');
insert into projects (id, title, color, city) values (908, 'vivamus metus arcu', 'Aquamarine', 'Persen');
insert into projects (id, title, color, city) values (909, 'morbi vel', 'Blue', 'Kolor');
insert into projects (id, title, color, city) values (910, 'pellentesque volutpat dui', 'Fuscia', 'Eastern Suburbs Mc');
insert into projects (id, title, color, city) values (911, 'eget', 'Goldenrod', 'Yongjiu');
insert into projects (id, title, color, city) values (912, 'lacus purus aliquet', 'Turquoise', 'Vladimirskaya');
insert into projects (id, title, color, city) values (913, 'dapibus at', 'Green', 'Tayturka');
insert into projects (id, title, color, city) values (914, 'a odio', 'Mauv', 'Piketberg');
insert into projects (id, title, color, city) values (915, 'tortor', null, 'Batagay-Alyta');
insert into projects (id, title, color, city) values (916, 'elementum eu interdum', 'Blue', 'Vaxholm');
insert into projects (id, title, color, city) values (917, 'nulla sed', 'Violet', 'Musina');
insert into projects (id, title, color, city) values (918, 'scelerisque', 'Turquoise', 'Afanas’yeva');
insert into projects (id, title, color, city) values (919, 'tincidunt', 'Teal', 'Sarmanovo');
insert into projects (id, title, color, city) values (920, 'orci vehicula condimentum', 'Yellow', 'Donghai');
insert into projects (id, title, color, city) values (921, 'accumsan tellus', 'Maroon', 'Waldbredimus');
insert into projects (id, title, color, city) values (922, 'augue vestibulum ante', 'Violet', 'Nāḩīyat Saddat al Hindīyah');
insert into projects (id, title, color, city) values (923, 'sem mauris laoreet', 'Purple', 'Zishan');
insert into projects (id, title, color, city) values (924, 'aenean', 'Fuscia', 'Smimou');
insert into projects (id, title, color, city) values (925, 'nulla integer', 'Aquamarine', 'Houxi');
insert into projects (id, title, color, city) values (926, 'nullam sit amet', 'Crimson', 'Jiangkou');
insert into projects (id, title, color, city) values (927, 'aliquam', null, 'Yukhnov');
insert into projects (id, title, color, city) values (928, 'adipiscing elit', 'Goldenrod', 'Nioki');
insert into projects (id, title, color, city) values (929, 'ut suscipit a', 'Aquamarine', 'Meilisi');
insert into projects (id, title, color, city) values (930, 'pede lobortis', 'Khaki', 'Lianfa');
insert into projects (id, title, color, city) values (931, 'ac neque duis', 'Teal', 'Habiganj');
insert into projects (id, title, color, city) values (932, 'mauris lacinia', 'Puce', 'Lyublino');
insert into projects (id, title, color, city) values (933, 'habitasse platea dictumst', 'Turquoise', 'Arlington');
insert into projects (id, title, color, city) values (934, 'mi pede', 'Violet', 'Mafeteng');
insert into projects (id, title, color, city) values (935, 'ut', 'Crimson', 'Mariano Moreno');
insert into projects (id, title, color, city) values (936, 'sed ante vivamus', 'Fuscia', 'Xuji');
insert into projects (id, title, color, city) values (937, 'tincidunt lacus', 'Purple', 'Saint John’s');
insert into projects (id, title, color, city) values (938, 'aliquam', 'Teal', 'Iida');
insert into projects (id, title, color, city) values (939, 'odio odio', 'Puce', 'Jincun');
insert into projects (id, title, color, city) values (940, 'non mi integer', null, 'San Mariano');
insert into projects (id, title, color, city) values (941, 'donec', 'Mauv', 'Xinglong');
insert into projects (id, title, color, city) values (942, 'at', 'Aquamarine', 'Feteira Grande');
insert into projects (id, title, color, city) values (943, 'vel', 'Puce', 'Sundsvall');
insert into projects (id, title, color, city) values (944, 'ipsum', 'Purple', 'Benešov nad Černou');
insert into projects (id, title, color, city) values (945, 'felis ut', 'Maroon', 'Oelaba');
insert into projects (id, title, color, city) values (946, 'enim leo', 'Yellow', 'El Bálsamo');
insert into projects (id, title, color, city) values (947, 'ac tellus', 'Puce', 'Cilated');
insert into projects (id, title, color, city) values (948, 'primis in faucibus', 'Blue', 'Huangma');
insert into projects (id, title, color, city) values (949, 'sit', 'Khaki', 'Tzaneen');
insert into projects (id, title, color, city) values (950, 'adipiscing lorem', null, 'Cigadog');
insert into projects (id, title, color, city) values (951, 'hendrerit at', null, 'Katsikás');
insert into projects (id, title, color, city) values (952, 'phasellus', 'Khaki', 'Boco');
insert into projects (id, title, color, city) values (953, 'diam erat', 'Orange', 'Göteborg');
insert into projects (id, title, color, city) values (954, 'sed vestibulum', 'Pink', 'Ruchihe');
insert into projects (id, title, color, city) values (955, 'diam cras pellentesque', 'Teal', 'Enhe Hada');
insert into projects (id, title, color, city) values (956, 'eget elit sodales', 'Turquoise', 'Praingkareha');
insert into projects (id, title, color, city) values (957, 'ante', null, 'Bandarbeyla');
insert into projects (id, title, color, city) values (958, 'vivamus', 'Red', 'Apitong');
insert into projects (id, title, color, city) values (959, 'in', 'Red', 'Izobil’nyy');
insert into projects (id, title, color, city) values (960, 'in felis eu', 'Puce', 'Taber');
insert into projects (id, title, color, city) values (961, 'ultrices vel augue', 'Violet', 'Rajadesa');
insert into projects (id, title, color, city) values (962, 'hendrerit at', 'Pink', 'Presidente Prudente');
insert into projects (id, title, color, city) values (963, 'sociis natoque penatibus', 'Maroon', 'Saint Petersburg');
insert into projects (id, title, color, city) values (964, 'morbi odio', 'Indigo', 'Grabovci');
insert into projects (id, title, color, city) values (965, 'mus', 'Green', 'Saint-Sauveur');
insert into projects (id, title, color, city) values (966, 'posuere', 'Fuscia', 'Jiangchi');
insert into projects (id, title, color, city) values (967, 'mauris vulputate elementum', 'Crimson', 'Mashi');
insert into projects (id, title, color, city) values (968, 'vestibulum', 'Orange', 'Courtaboeuf');
insert into projects (id, title, color, city) values (969, 'sapien non mi', 'Maroon', 'Hällefors');
insert into projects (id, title, color, city) values (970, 'ac', 'Purple', 'Foso');
insert into projects (id, title, color, city) values (971, 'id turpis', 'Goldenrod', 'Laoxingchang');
insert into projects (id, title, color, city) values (972, 'semper porta', 'Aquamarine', 'Ramadi');
insert into projects (id, title, color, city) values (973, 'quis lectus', 'Yellow', 'Mirontsi');
insert into projects (id, title, color, city) values (974, 'consequat nulla nisl', null, 'Gerong');
insert into projects (id, title, color, city) values (975, 'ut', 'Blue', 'Mondokan');
insert into projects (id, title, color, city) values (976, 'lobortis', 'Turquoise', 'Uchkeken');
insert into projects (id, title, color, city) values (977, 'sit amet', 'Indigo', 'Paciran');
insert into projects (id, title, color, city) values (978, 'tristique', 'Violet', 'Jakšić');
insert into projects (id, title, color, city) values (979, 'lorem', null, 'Inđija');
insert into projects (id, title, color, city) values (980, 'tristique in tempus', 'Pink', 'Kamaris');
insert into projects (id, title, color, city) values (981, 'integer', 'Orange', 'Changxi');
insert into projects (id, title, color, city) values (982, 'sit', 'Khaki', 'Uruguaiana');
insert into projects (id, title, color, city) values (983, 'vestibulum', 'Blue', 'Angren');
insert into projects (id, title, color, city) values (984, 'interdum', 'Orange', 'Winneba');
insert into projects (id, title, color, city) values (985, 'mauris enim', 'Blue', 'Zbąszyń');
insert into projects (id, title, color, city) values (986, 'tempus', 'Maroon', 'Huanghua');
insert into projects (id, title, color, city) values (987, 'molestie hendrerit at', 'Teal', 'Tunasbaru');
insert into projects (id, title, color, city) values (988, 'pharetra magna ac', 'Blue', 'Rondonópolis');
insert into projects (id, title, color, city) values (989, 'magnis dis', null, 'Ljubuški');
insert into projects (id, title, color, city) values (990, 'in faucibus orci', 'Green', 'Serang');
insert into projects (id, title, color, city) values (991, 'justo nec', 'Teal', 'Vir');
insert into projects (id, title, color, city) values (992, 'tristique in', 'Maroon', 'Xinshi');
insert into projects (id, title, color, city) values (993, 'turpis', 'Violet', 'Delicias');
insert into projects (id, title, color, city) values (994, 'nulla', 'Indigo', '‘Alāqahdārī Gēlān');
insert into projects (id, title, color, city) values (995, 'aenean sit amet', null, 'São Luiz Gonzaga');
insert into projects (id, title, color, city) values (996, 'libero', null, 'Namasuba');
insert into projects (id, title, color, city) values (997, 'augue', null, 'Azua');
insert into projects (id, title, color, city) values (998, 'quisque ut', 'Goldenrod', 'Liuhou');
insert into projects (id, title, color, city) values (999, 'ligula', 'Maroon', 'Teresa');
insert into projects (id, title, color, city) values (1000, 'elementum eu', 'Teal', 'Artesianón');
